/* TankMates offline scanner: on-device species ID (MobileNetV3 features + kNN on our reference library) and a visual symptom checker. No data leaves the device. */
(()=>{
const A=window.APP,D=window.DRAW,I=D.i,CI=D.ci,esc=A.esc;
const TF='https://cdnjs.cloudflare.com/ajax/libs/tensorflow/4.22.0/tf.min.js';
let st={mode:'cam',img:null,res:null,q:null,sym:[],busy:false,err:null,stream:null},model=null,ref=null,loading=null,GATE=null,IW=null,IB=null,AQ=null;const NOFISH=.35,LOCKFISH=.5;
function loadScript(src){return new Promise((ok,no)=>{if(window.tf)return ok();const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=()=>no(new Error('Could not load the scanner engine'));document.head.appendChild(s)})}
async function ensure(){if(window.__noDino!==true){try{await dEnsure();return}catch(e){console.warn('dino',e);window.__noDino=true}}if(model&&ref)return;if(loading)return loading;loading=(async()=>{await loadScript(TF);await tf.ready();
 const [m,idx,bin,cj,cb]=await Promise.all([tf.loadGraphModel('model/model.json'),fetch('data/emb.json').then(r=>r.json()),fetch('data/emb.wasm').then(r=>r.arrayBuffer()),fetch('data/clf.json').then(r=>r.json()),fetch('data/clf.wasm').then(r=>r.arrayBuffer())]);
 model=m;const u8=new Uint8Array(bin),n=idx.lab.length,d=idx.dim,f=new Float32Array(n*d);
 for(let i=0;i<n;i++){let s=0;for(let j=0;j<d;j++){const v=u8[i*d+j];f[i*d+j]=v;s+=v*v}s=Math.sqrt(s)||1;for(let j=0;j<d;j++)f[i*d+j]/=s}
 ref={f,lab:idx.lab,ids:idx.ids,d,n,W:new Int8Array(cb),cs:cj.scale,T:cj.T,b:cj.b,mu:cj.mu,cal:cj.cal,kw:cj.kw};
 try{const [gj,ij,ib]=await Promise.all([fetch('data/gate.json').then(r=>r.json()),fetch('data/inet.json').then(r=>r.json()),fetch('data/inet.wasm').then(r=>{if(!r.ok)throw 0;return r.arrayBuffer()})]);const q=new Int8Array(ib),K=ij.b.length,w=new Float32Array(q.length);for(let i=0;i<1024;i++)for(let k=0;k<K;k++)w[i*K+k]=q[i*K+k]*ij.s[k];IW=tf.tensor2d(w,[1024,K]);IB=tf.tensor1d(ij.b);AQ=tf.tensor1d(ij.aq,'int32');GATE=gj}catch(e){GATE=null}})();try{await loading}catch(e){loading=null;throw e}}
async function embedFrom(canvas){const [f,a]=tf.tidy(()=>{const x=tf.browser.fromPixels(canvas).toFloat().div(255).expandDims(0);const crops=[x,tf.image.flipLeftRight(x)];const out=model.predict(tf.concat(crops,0));const f=out.relu().mean(0);const a=IW?tf.softmax(out.matMul(IW).add(IB)).mean(0).gather(AQ).sum():tf.scalar(-1);return [f,a]});const v=await f.data(),av=(await a.data())[0];f.dispose();a.dispose();v.aq=av;return v}
/* is there a fish / plant / aquarium animal in this crop? logistic gate trained on 4,500 aquarium photos vs 4,000 everyday images */
function gateOf(q,aq){if(!GATE||aq<0)return 1;let z=GATE.b+GATE.wa*Math.log(aq+1e-4)/5;for(let j=0;j<1024;j++)z+=GATE.w[j]*q[j];return 1/(1+Math.exp(-z))}
function toCanvas(img,box){const c=document.createElement('canvas');c.width=c.height=224;const g=c.getContext('2d');const w=img.naturalWidth||img.width,h=img.naturalHeight||img.height;let [x,y,s]=box||[0,0,Math.min(w,h)];if(!box){x=(w-s)/2;y=(h-s)/2}g.drawImage(img,x,y,s,s,0,0,224,224);return c}
function quality(img){const c=document.createElement('canvas'),W=160,H=Math.round(160*(img.naturalHeight/img.naturalWidth))||120;c.width=W;c.height=H;const g=c.getContext('2d');g.drawImage(img,0,0,W,H);const d=g.getImageData(0,0,W,H).data;let sum=0,lap=0,n=0,gray=new Float32Array(W*H);
 for(let i=0;i<W*H;i++){const v=.299*d[i*4]+.587*d[i*4+1]+.114*d[i*4+2];gray[i]=v;sum+=v}const mean=sum/(W*H);
 for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++){const i=y*W+x,l=4*gray[i]-gray[i-1]-gray[i+1]-gray[i-W]-gray[i+W];lap+=l*l;n++}const sharp=lap/n;
 return{bright:mean,sharp,okB:mean>45&&mean<225,okS:sharp>60,okR:Math.min(img.naturalWidth,img.naturalHeight)>=300}}
async function qvecs(img){await ensure();const w=img.naturalWidth,h=img.naturalHeight,s=Math.min(w,h);
 const s7=s*.72,boxes=[null,[(w-s*.8)/2,(h-s*.8)/2,s*.8],[(w-s7)/2,Math.max(0,(h-s)/2),s7],[(w-s7)/2,Math.min(h-s7,(h+s)/2-s7),s7]];const qs=[];let g=0;for(const b of boxes){const v=await embedFrom(toCanvas(img,b));let nn=0;for(const x of v)nn+=x*x;nn=Math.sqrt(nn)||1;const q=Float32Array.from(v,x=>x/nn);g=Math.max(g,gateOf(q,v.aq));qs.push(q)}qs.fish=g;return qs}
async function identify(img,live){if(window.__noDino!==true){try{return await dIdentify(img,live)}catch(e){console.warn('dino',e);window.__noDino=true}}const qs=await qvecs(img);
 const {f,lab,ids,d,n,W,cs,T,b,mu}=ref,C=ids.length,best={};for(let i=0;i<n;i++){let m=-1;for(const q of qs){let s2=0;const o=i*d;for(let j=0;j<d;j++)s2+=q[j]*f[o+j];if(s2>m)m=s2}const id=ids[lab[i]];(best[id]=best[id]||[]).push(m)}
 const raw=Math.max(...Object.values(best).map(a=>Math.max(...a)));
 const L=new Float32Array(C);for(const q of qs){const g=q.map((x,j)=>x-mu[j]);let nn=0;for(const x of g)nn+=x*x;nn=Math.sqrt(nn)||1;for(let c=0;c<C;c++){let z=b[c];for(let j=0;j<d;j++)z+=g[j]/nn*W[j*C+c]*cs;L[c]+=z*T/qs.length*(ref.cal||0.4)}}
 for(let c=0;c<C;c++){const a=(best[ids[c]]||[0]).sort((x,y)=>y-x).slice(0,3);L[c]+=(ref.kw||0)*(a.reduce((s3,v)=>s3+v,0)/a.length)}
 const mx=Math.max(...L);let Z=0;const P=Array.from(L,z=>{const e=Math.exp(z-mx);Z+=e;return e});
 const ex=P.map((e,c)=>[ids[c],e/Z]).sort((a,b2)=>b2[1]-a[1]);
 window.__scanFish=qs.fish;const top=ex.slice(0,8).map(([id,p])=>({id,p})).filter(o=>A.BY[o.id]);const sure=top.length>0&&top[0].p>=.7&&(top[0].p-(top[1]?top[1].p:0))>=.4&&raw>=.6;return{top,raw,sure,fish:qs.fish==null?1:qs.fish}}

/* ===== DINOv2 engine (Apache-2.0): animal/plant/other check + species prototypes + calibrated head. Runs on-device with onnxruntime-web. ===== */
let DN=null,dLoading=null;
async function dEnsure(){if(DN)return DN;if(dLoading)return dLoading;dLoading=(async()=>{
 if(!window.ort)await new Promise((ok,no)=>{const s=document.createElement('script');s.src='ort/ort.wasm.min.js';s.onload=ok;s.onerror=()=>no(new Error('Could not load the scanner engine'));document.head.appendChild(s)});
 ort.env.wasm.wasmPaths='https://cdn.jsdelivr.net/npm/onnxruntime-web@1.20.1/dist/';ort.env.wasm.numThreads=1;
 const gb=u=>fetch(u).then(r=>{if(!r.ok)throw new Error('missing '+u);return r.arrayBuffer()});
 if(!window.SCANPH){const sc=document.createElement('script');sc.src='data/scanph.js';sc.async=true;document.head.appendChild(sc)}
 const [p0a,p0b,p1a,p1b,meta,bin]=await Promise.all([gb('ort/dino0a.wasm'),gb('ort/dino0b.wasm'),gb('ort/dino1a.wasm'),gb('ort/dino1b.wasm'),fetch('data/dino.json').then(r=>r.json()),gb('data/dino.wasm')]);
 const _pp=[p0a,p0b,p1a,p1b],buf=new Uint8Array(_pp.reduce((a,b)=>a+b.byteLength,0));{let _o=0;for(const x of _pp){buf.set(new Uint8Array(x),_o);_o+=x.byteLength}}
 const sess=await ort.InferenceSession.create(buf,{executionProviders:['wasm'],graphOptimizationLevel:'all'});
 const q=new Int8Array(bin),d=meta.d,np=meta.np,C=meta.ids.length;let o=0;
 const P=new Float32Array(np*d);for(let i=0;i<np;i++){let n=0;for(let j=0;j<d;j++){const v=q[o+i*d+j];P[i*d+j]=v;n+=v*v}n=Math.sqrt(n)||1;for(let j=0;j<d;j++)P[i*d+j]/=n}o+=np*d;
 const W=new Float32Array(d*C);for(let i=0;i<d*C;i++)W[i]=q[o+i]*meta.sW/127;o+=d*C;
 const G=new Float32Array(d*3);for(let i=0;i<d*3;i++)G[i]=q[o+i]*meta.sG/127;
 DN={sess,P,W,G,meta,C,d,np};return DN})();try{return await dLoading}catch(e){dLoading=null;throw e}}
const DM=[0.485,0.456,0.406],DS=[0.229,0.224,0.225];
function padCanvas(img){const c=document.createElement('canvas');c.width=c.height=224;const g=c.getContext('2d');g.fillStyle='rgb(40,70,80)';g.fillRect(0,0,224,224);const w=img.naturalWidth||img.videoWidth||img.width,h=img.naturalHeight||img.videoHeight||img.height,s=224/Math.max(w,h);g.drawImage(img,(224-w*s)/2,(224-h*s)/2,w*s,h*s);return c}
async function dFeats(canvases){const B=canvases.length,x=new Float32Array(B*3*224*224);
 canvases.forEach((c,b)=>{const d=c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,224,224).data;for(let i=0;i<224*224;i++){for(let k=0;k<3;k++)x[b*3*50176+k*50176+i]=(d[i*4+k]/255-DM[k])/DS[k]}});
 const out=await DN.sess.run({pixel_values:new ort.Tensor('float32',x,[B,3,224,224])});const h=out[Object.keys(out)[0]].data,T=257,H=384,F=[];
 for(let b=0;b<B;b++){const f=new Float32Array(768);for(let j=0;j<H;j++)f[j]=h[b*T*H+j];for(let t=1;t<T;t++){const o=b*T*H+t*H;for(let j=0;j<H;j++)f[H+j]+=h[o+j]}for(let j=0;j<H;j++)f[H+j]/=T-1;let n=0;for(const v of f)n+=v*v;n=Math.sqrt(n)||1;for(let j=0;j<768;j++)f[j]/=n;F.push(f)}return F}
const TWINS={neon:['cardinal','greenneon'],cardinal:['neon','greenneon'],greenneon:['neon','cardinal'],rummynose:['brilliantrummy'],brilliantrummy:['rummynose'],guppy:['endler'],endler:['guppy'],molly:['sailfinmolly','yucatanmolly'],sailfinmolly:['molly','yucatanmolly'],yucatanmolly:['molly','sailfinmolly'],goldfish:['comet','shubunkin'],comet:['goldfish','shubunkin'],shubunkin:['goldfish','comet'],crystalred:['bluebolt','taiwanbee'],bluebolt:['crystalred','taiwanbee'],taiwanbee:['crystalred','bluebolt'],vampcrab:['thaidevil'],thaidevil:['vampcrab'],harlequin:['lambchop'],lambchop:['harlequin']};
async function dIdentify(img,live){await dEnsure();const {P,W,G,meta,C,d,np}=DN;const w=img.naturalWidth||img.videoWidth||img.width,h=img.naturalHeight||img.videoHeight||img.height,s=Math.min(w,h),s7=s*.72;
 const boxes=live?[null]:[null,[(w-s*.8)/2,(h-s*.8)/2,s*.8],[(w-s7)/2,Math.max(0,(h-s)/2),s7],[(w-s7)/2,Math.min(h-s7,(h+s)/2-s7),s7]];
 const cv=boxes.map(b=>toCanvas(img,b));cv.push(padCanvas(img));const F=await dFeats(cv);
 const acc=new Float64Array(C);let wsum=0,fish=0,plant=0,raw=0;
 for(const f of F){const gz=[0,1,2].map(k=>{let z=meta.gb[k];for(let j=0;j<d;j++)z+=f[j]*G[j*3+k];return z*meta.gT});const gm=Math.max(...gz),ge=gz.map(z=>Math.exp(z-gm)),gs=ge[0]+ge[1]+ge[2];const pa=ge[0]/gs,pp=ge[1]/gs;fish=Math.max(fish,pa);plant=Math.max(plant,pp);
  const kn=new Float32Array(C).fill(-1);for(let i=0;i<np;i++){let v=0;const o=i*d;for(let j=0;j<d;j++)v+=f[j]*P[o+j];const c=meta.pl[i];if(v>kn[c])kn[c]=v;if(meta.kind[c]===0&&v>raw)raw=v}
  const z=new Float64Array(C);let zm=-1e9;for(let c=0;c<C;c++){let v=meta.b[c];for(let j=0;j<d;j++)v+=f[j]*W[j*C+c];z[c]=(v*meta.T0+meta.a*kn[c])*meta.T;if(z[c]>zm)zm=z[c]}
  let zs=0;for(let c=0;c<C;c++){z[c]=Math.exp(z[c]-zm);zs+=z[c]}const wt=pa+pp+.05;for(let c=0;c<C;c++)acc[c]+=wt*z[c]/zs;wsum+=wt}
 fish*=Math.max(0,Math.min(1,(raw-.40)/.10));
 const ex=[...acc].map((v,c)=>[meta.ids[c],v/wsum,meta.kind[c]]).sort((a,b)=>b[1]-a[1]);
 const animals=ex.filter(e=>e[2]===0),plants=ex.filter(e=>e[2]===1);
 const top=animals.slice(0,8).map(([id,p])=>({id,p})).filter(o=>A.BY[o.id]);const ptop=plants.slice(0,3).map(([id,p])=>({id,p}));
 const ap=animals.reduce((s2,e)=>s2+e[1],0)||1;top.forEach(o=>o.p=o.p/ap);
 let sure=top.length>0&&top[0].p>=.8&&(top[0].p-(top[1]?top[1].p:0))>=.4&&fish>=.6;
 if(top.length&&TWINS[top[0].id]){sure=false;TWINS[top[0].id].forEach((t,k)=>{if(A.BY[t]&&!top.slice(0,3).some(o=>o.id===t)){const i=top.findIndex(o=>o.id===t);const o=i>=0?top.splice(i,1)[0]:{id:t,p:.01};top.splice(1+k,0,o)}})}const known=sure||(top.length>0&&top[0].p>=.2&&raw>=.55);
 return{top,ptop,raw,sure,known,fish,plant,engine:'dino'}}
const ring=p=>{const r=27,c=2*Math.PI*r,col=p>.6?'#45D483':p>.3?'#F6B740':'#FF6A57';return `<svg class="conf" viewBox="0 0 66 66"><circle cx="33" cy="33" r="${r}" fill="none" stroke="#1C4351" stroke-width="7"/><circle cx="33" cy="33" r="${r}" fill="none" stroke="${col}" stroke-width="7" stroke-linecap="round" stroke-dasharray="${c}" stroke-dashoffset="${c*(1-p)}" transform="rotate(-90 33 33)"/><text x="33" y="38" text-anchor="middle" font-size="15" font-weight="800" fill="#fff">${Math.round(p*100)}%</text></svg>`};
const guideSvg=`<svg class="guide" viewBox="0 0 240 140" aria-hidden="true"><g fill="none" stroke="#fff" stroke-width="2.4" stroke-dasharray="7 6"><path d="M30 70 C60 22 150 18 190 62 L226 34 L218 70 L226 106 L190 78 C150 122 60 118 30 70Z"/><circle cx="58" cy="62" r="5"/></g></svg>`;
function noFishHtml(live){const r=st.res||{},pl=r.plant>.6;const pt=pl&&r.ptop&&r.ptop[0]&&r.ptop[0].p>.6&&A.BY[r.ptop[0].id]?A.BY[r.ptop[0].id]:null;return `<div class="${live?'lvres nofish':'res nofish'}"><span class="nfic">${I(pl?'leaf':'search',26)}</span><div class="nft"><b>${pl?'That looks like a plant, not a fish':'I can\'t recognise anything here'}</b>${pt?`<button class="lnk" data-open="${pt.id}" style="display:block;margin:4px 0">Could be: ${esc(pt.n)} ›</button>`:''}<span>${pl?'I only identify fish and other aquarium animals for now.':'I couldn\'t find a fish, shrimp, snail or other aquarium animal in this photo.'} Fill the frame with one animal, side on, with the tank light on.</span></div><div class="nfb"><button class="btn sm grad" data-sc="again">${I('camera',15)}Try again</button><button class="btn sm ghost" data-sc="nonematch">${I('search',15)}Search by name</button></div></div>`}
function resView(){const r=st.res;if(r.fish<NOFISH&&!st.nfShow)return noFishHtml(false);if(st.picked&&A.BY[st.picked])return pickedCard(r,false);if(r.known===false&&!st.showPick)return unknownHtml(r,false);if(!r.sure||st.showPick)return pickHtml(r,false);const t=r.top[0],x=A.BY[t.id];const low=t.p<.4||r.raw<.55;
 return `<div class="res"><div style="display:flex;gap:12px;align-items:center">${ring(low?Math.min(t.p,r.raw*.7):t.p)}<div style="min-width:0"><span class="xs" style="color:#93B6B1;font-weight:800;text-transform:uppercase;letter-spacing:.06em">${low?'Best guess':'Most likely'}</span><h3 style="font-size:21px;margin:2px 0">${esc(x.n)}</h3><i class="sm" style="color:#93B6B1">${esc(x.sci)}</i></div><img src="${D.src(x.id)}" alt="" style="width:96px;height:66px;object-fit:contain;margin-left:auto"></div>
 ${low?`<p class="sm" style="color:#F6B740;margin-top:10px">${I('alert',15)} Low confidence. Try a sharper, side-on photo, or compare with the options below.</p>`:''}
 <div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button class="btn sm grad" data-open="${x.id}">${I('book',15)}Open profile</button><button class="btn sm ghost" style="color:#fff" data-addplan="${x.id}">${I('plus',15)}Add to a tank</button><button class="btn sm ghost" style="color:#fff" data-sc="sym">${I('virus',15)}Check its health</button></div>
 <button class="lnk xs scnot" data-sc="showpick" style="margin-top:10px">Not right? Compare with similar fish</button></div>`}
/* ===== Health scan: photo -> visible-sign analysis + behaviour check -> score, likely causes, first aid ===== */
const BEH=[['eat','Not eating','noeat',12],['gasping','Gasping at the surface','gasping',15],['clamped','Fins clamped to the body','clamped',8],['flashing','Rubbing on decor','flashing',8],['hide','Hiding or very still','lethargic',8],['upsidedown','Swimming sideways / struggling','upsidedown',18],['dust','Looks dusty gold under a torch','golddust',14]];
const refCache={};
function px(img,W){const s=W/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height);const c=document.createElement('canvas');c.width=Math.max(8,Math.round((img.naturalWidth||img.width)*s));c.height=Math.max(8,Math.round((img.naturalHeight||img.height)*s));const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(img,0,0,c.width,c.height);return{c,g,w:c.width,h:c.height,d:g.getImageData(0,0,c.width,c.height).data}}
function colourStats(P,mask){let n=0,sat=0,red=0;for(let i=0;i<P.w*P.h;i++){if(!mask[i])continue;const r=P.d[i*4],g=P.d[i*4+1],b=P.d[i*4+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);n++;sat+=mx?(mx-mn)/mx:0;if(r>140&&r>g*1.6&&r>b*1.5)red++}return{sat:n?sat/n:0,red:n?red/n:0,n}}
function refStats(id){if(refCache[id])return refCache[id];refCache[id]=new Promise(ok=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>{try{const P=px(im,160);const m=new Uint8Array(P.w*P.h);for(let i=0;i<m.length;i++)m[i]=P.d[i*4+3]>200?1:0;ok(colourStats(P,m))}catch(e){ok(null)}};im.onerror=()=>ok(null);im.src=D.src(id)});return refCache[id]}
function comps(P,cand){const W=P.w,H=P.h,seen=new Uint8Array(W*H),out=[];for(let i=0;i<W*H;i++){if(!cand[i]||seen[i])continue;const q=[i];seen[i]=1;let a=0,x0=W,x1=0,y0=H,y1=0,edge=false;while(q.length){const j=q.pop();a++;const x=j%W,y=(j/W)|0;if(x<x0)x0=x;if(x>x1)x1=x;if(y<y0)y0=y;if(y>y1)y1=y;if(x<2||y<2||x>W-3||y>H-3)edge=true;for(const k of [j-1,j+1,j-W,j+W])if(k>=0&&k<W*H&&cand[k]&&!seen[k]){seen[k]=1;q.push(k)}}out.push({a,x:(x0+x1)/2,y:(y0+y1)/2,r:Math.max(x1-x0,y1-y0)/2+1,bw:x1-x0+1,bh:y1-y0+1,edge})}return out}
function feats(img){const P=px(img,640),W=P.w,H=P.h,N=W*H,d=P.d;
 let br=0,bg=0,bb=0,bn=0;for(let x=0;x<W;x++)for(const y of [0,1,H-2,H-1]){const i=(y*W+x)*4;br+=d[i];bg+=d[i+1];bb+=d[i+2];bn++}for(let y=0;y<H;y++)for(const x of [0,1,W-2,W-1]){const i=(y*W+x)*4;br+=d[i];bg+=d[i+1];bb+=d[i+2];bn++}br/=bn;bg/=bn;bb/=bn;
 const L=new Float32Array(N),S=new Float32Array(N),mask=new Uint8Array(N);let lum=0;
 for(let i=0;i<N;i++){const r=d[i*4],g=d[i*4+1],b=d[i*4+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);L[i]=.299*r+.587*g+.114*b;S[i]=mx?(mx-mn)/mx:0;lum+=L[i];const x=i%W,y=(i/W)|0,cx=(x/W-.5)/.46,cy=(y/H-.5)/.42;mask[i]=(cx*cx+cy*cy<1&&Math.hypot(r-br,g-bg,b-bb)>38)?1:0}
 lum/=N;let mN=0;for(let i=0;i<N;i++)mN+=mask[i];if(mN<N*.04){mN=0;for(let i=0;i<N;i++){const x=i%W,y=(i/W)|0,cx=(x/W-.5)/.42,cy=(y/H-.5)/.36;mask[i]=cx*cx+cy*cy<1?1:0;mN+=mask[i]}}
 const integ=A2=>{const I=new Float32Array((W+1)*(H+1));for(let y=0;y<H;y++){let s=0;for(let x=0;x<W;x++){s+=A2[y*W+x];I[(y+1)*(W+1)+x+1]=I[y*(W+1)+x+1]+s}}return(x,y,r)=>{const x0=Math.max(0,x-r),y0=Math.max(0,y-r),x1=Math.min(W,x+r+1),y1=Math.min(H,y+r+1);return(I[y1*(W+1)+x1]-I[y0*(W+1)+x1]-I[y1*(W+1)+x0]+I[y0*(W+1)+x0])/((x1-x0)*(y1-y0))}};
 const bL=integ(L),bS=integ(S);
 const white=new Uint8Array(N),gold=new Uint8Array(N),pw=new Uint8Array(N);let sharp=0;
 for(let i=0;i<N;i++){if(!mask[i])continue;const x=i%W,y=(i/W)|0,r=d[i*4],g=d[i*4+1],b=d[i*4+2];const mL=bL(x,y,4),lc=L[i]-mL;
  if(L[i]>185&&S[i]<.22&&lc>45&&bS(x,y,4)>.24)white[i]=1;if(L[i]>195&&S[i]<.16)pw[i]=1;
  if(r>150&&g>120&&b<110&&r-b>70&&L[i]-bL(x,y,3)>22&&S[i]>.35)gold[i]=1;
  if(x>0&&y>0&&x<W-1&&y<H-1){const l=4*L[i]-L[i-1]-L[i+1]-L[i-W]-L[i+W];sharp+=l*l}}
 sharp/=Math.max(1,mN);
 const wc=comps(P,white).filter(c=>!c.edge);const iso=c=>{const cx=Math.round(c.x),cy=Math.round(c.y),Lc=L[cy*W+cx];let ok=0;for(let k=0;k<8;k++){const an=k*Math.PI/4,rr=c.r+2.5,x=Math.round(cx+Math.cos(an)*rr),y=Math.round(cy+Math.sin(an)*rr);if(x<0||y<0||x>=W||y>=H)continue;if(L[y*W+x]<Lc-40&&S[y*W+x]>.2)ok++}return ok>=7};const spots=wc.filter(c=>c.a<=16&&iso(c)),ring=(c,need)=>{let ok=0,n=0;for(let k=0;k<12;k++){const an=k*Math.PI/6,rr=c.r+9,x=Math.round(c.x+Math.cos(an)*rr),y=Math.round(c.y+Math.sin(an)*rr);n++;if(x<0||y<0||x>=W||y>=H)continue;const j=y*W+x;if(mask[j]&&S[j]>.25&&L[j]<205)ok++}return ok>=need},patches=comps(P,pw).filter(c=>!c.edge&&c.a>=150&&c.a<=8000&&c.a/(4*c.r*c.r)>.3&&ring(c,9));
 const gc=comps(P,gold).filter(c=>!c.edge&&c.a<=6);const cs=colourStats(P,mask);
 return{W,H,spots,patches,gold:gc,red:cs.red,sat:cs.sat,lum,sharp,area:mN}}
function refFeats(id){const k='f_'+id;if(refCache[k])return refCache[k];refCache[k]=new Promise(ok=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>{try{const c=document.createElement('canvas');c.width=im.width*1.33;c.height=im.height*1.33;const g=c.getContext('2d');g.fillStyle='#123028';g.fillRect(0,0,c.width,c.height);g.drawImage(im,(c.width-im.width)/2,(c.height-im.height)/2);ok(feats(c))}catch(e){ok(null)}};im.onerror=()=>ok(null);im.src=D.src(id)});return refCache[k]}
window.__eyeCheck=img=>eyeCheck(img);function eyeCheck(img){const P=px(img,480),W=P.w,H=P.h,N=W*H,d=P.d,L=new Float32Array(N),S=new Float32Array(N),cand=new Uint8Array(N);
 for(let i=0;i<N;i++){const r=d[i*4],g=d[i*4+1],b=d[i*4+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);L[i]=.299*r+.587*g+.114*b;S[i]=mx?(mx-mn)/mx:0;cand[i]=(L[i]>140&&S[i]<.3)?1:0}
 const out=[];for(const c of comps(P,cand)){if(c.edge)continue;const fr=c.a/N;if(fr<.0015||fr>.06)continue;
  const w=c.bw,h=c.bh;if(!w||!h)continue;const ar=w/h;if(ar<.6||ar>1.65)continue;const fill=c.a/(w*h);if(fill<.55)continue;
  const r=(w+h)/4;let ring=0,n=0;for(let k=0;k<16;k++){const an=k*Math.PI/8,x=Math.round(c.x+Math.cos(an)*r*1.45),y=Math.round(c.y+Math.sin(an)*r*1.45);if(x<0||y<0||x>=W||y>=H)continue;n++;const j=y*W+x;if(S[j]>.35&&L[j]>45)ring++}
  if(ring<10)continue;
  let dark=0,tot=0;for(let y=Math.round(c.y-r*.5);y<=c.y+r*.5;y++)for(let x=Math.round(c.x-r*.5);x<=c.x+r*.5;x++){if(x<0||y<0||x>=W||y>=H)continue;tot++;if(L[y*W+x]<70)dark++}
  if(tot&&dark/tot<.08)out.push({x:c.x,y:c.y,r,a:c.a,ring,fill})}
 return{W,eyes:out}}
async function analyzeHealth(img,spId){const f=feats(img),ref=spId?await refFeats(spId):null;const F=[];
 const base=ref?{spots:ref.spots.length,patches:ref.patches.length,gold:ref.gold.length,red:ref.red,sat:ref.sat}:{spots:2,patches:1,gold:Math.round(f.area*.01),red:null,sat:null};
 const exS=f.spots.length-Math.round(base.spots*1.25)-2;
 if(exS>=10)F.push({k:'whitedots',l:`${f.spots.length} tiny white spots on the body or fins`,sev:3,pts:f.spots,col:'#F8FAFC'});else if(exS>=5)F.push({k:'whitedots',l:`${f.spots.length} small white specks, possibly white spot (ich)`,sev:2,pts:f.spots,col:'#F8FAFC',maybe:1});
 const exP=f.patches.length-base.patches,pArea=f.patches.reduce((a,c)=>a+c.a,0);
 if(exP>=1&&pArea>f.W*f.H*.0012)F.push({k:'cotton',l:`${f.patches.length} fuzzy white patch${f.patches.length>1?'es':''}, possibly fungus`,sev:2,pts:f.patches,col:'#E2E8F0',maybe:exP<2?1:0});
 try{const ec=eyeCheck(img);window.__eye=JSON.stringify(ec.eyes.map(e=>[Math.round(e.x),Math.round(e.y),Math.round(e.r),e.ring]));if(ec.eyes.length){const k=f.W/ec.W;const big=ec.eyes.some(e=>e.a/(ec.W*ec.W)>.012);F.unshift({k:'cloudyeye',l:ec.eyes.length>1?'Both eyes look cloudy or white instead of dark':'Eye looks cloudy or milky white instead of dark',sev:3,pts:ec.eyes.map(e=>({x:e.x*k,y:e.y*k,r:e.r*k/1.8})),col:'#E0F2FE',maybe:0});if(big)F.push({k:'bulgeye',l:'The eye may be swollen or bulging',sev:2,pts:[],col:'#F59E0B',maybe:1})}}catch(_){}
 /* gold dust (velvet) is too subtle for a phone photo: asked as a question instead */
 if(base.red!=null&&f.red-base.red>.08)F.push({k:'redsores',l:'More red on the body or fins than this species normally shows',sev:2,pts:[],col:'#EF4444',maybe:f.red-base.red<.15?1:0});
 if(base.sat!=null&&base.sat>.3&&f.sat<base.sat*.5)F.push({k:'fadedpatch',l:'Colours look faded compared with a healthy one',sev:1,pts:[],col:'#94A3B8',maybe:1});
 const qual=f.lum<45?'Photo is quite dark, so small signs can be missed.':f.sharp<25?'Photo is a little blurry, so small signs can be missed.':!spId?'Species not recognised, so colour checks were skipped.':'';
 const o=document.createElement('canvas');const nw=img.naturalWidth||img.width,nh=img.naturalHeight||img.height,ow=Math.min(900,nw);o.width=ow;o.height=Math.round(nh*ow/nw);const og=o.getContext('2d');og.drawImage(img,0,0,o.width,o.height);const k=o.width/f.W;
 F.forEach(x=>{og.strokeStyle=x.k==='whitedots'?'#22D3EE':x.k==='cotton'?'#A78BFA':x.k==='golddust'?'#FBBF24':'#F43F5E';og.lineWidth=Math.max(2,o.width/260);x.pts.slice(0,40).forEach(p=>{og.beginPath();og.arc(p.x*k,p.y*k,Math.max(6,p.r*k*1.8),0,Math.PI*2);og.stroke()})});
 return{F,qual,overlay:o.toDataURL('image/jpeg',.85),stats:{f:{s:f.spots.length,p:f.patches.length,g:f.gold.length,red:f.red,sat:f.sat},ref:ref&&{s:ref.spots.length,p:ref.patches.length,g:ref.gold.length,red:ref.red,sat:ref.sat}}}}
function healthScore(){const h=st.h;if(!h||!h.an)return null;let s=100;h.an.F.forEach(f=>s-=f.maybe?f.sev*7:f.sev*13);BEH.forEach(([k,,,w])=>{if(h.beh[k])s-=w});(st.sym||[]).forEach(()=>s-=6);return sevCap(Math.max(5,Math.min(100,Math.round(s))))}
function sevCap(s){try{const dz=rankDz(healthKeys());if(dz.length&&dz[0][0]){const c=[100,78,60,40][dz[0][0].sev]||100;return Math.min(s,c)}}catch(e){}return s}
function healthKeys(){const h=st.h,ks=new Set(st.sym||[]);if(h&&h.an)h.an.F.forEach(f=>{if(!(f.maybe&&f.k==='bulgeye'))ks.add(f.k)});BEH.forEach(([k,,sk])=>{if(h&&h.beh[k]&&sk&&window.SYM[sk])ks.add(sk)});return[...ks]}
function rankDz(keys){if(!keys.length)return[];return window.DZ.map(d=>{const hit=d.sym.filter(s=>keys.includes(s)).length;return[d,hit?hit/Math.sqrt(d.sym.length*keys.length)+d.sev*.01:0]}).filter(a=>a[1]>0).sort((a,b)=>b[1]-a[1]).slice(0,3)}
function runHealthForce(img,m){return runHealth(img,m,true)}
async function runHealth(img,m,force){st.h={img,an:null,busy:true,beh:(st.h&&st.h.beh)||{},sp:null,force:!!force};render(m);
 let sp=null;try{await ensure();const r=await identify(img);if(r&&r.fish<NOFISH&&!st.h.force){st.h.busy=false;st.h.nofish=true;render(m);return}if(r&&r.top&&r.top[0]&&r.top[0].p>.35&&r.fish>=LOCKFISH)sp=r.top[0].id}catch(e){}
 try{st.h.sp=sp;st.h.an=await analyzeHealth(img,sp);window.__hs=JSON.stringify(st.h.an.stats)+' sp='+sp}catch(e){st.h.err='Could not analyse this photo. Try another one.'}st.h.busy=false;
 try{const n=A.stat('healthchecks');A.xp(15,'Health check');if(n>=5)A.award('doctor')}catch(e){}if(A.S.sheet==='scan')render(m)}
/* ---- AI vet check: Claude vision on the viewer's account (only where available) ---- */
let AIS=null,aiImg=false;(async()=>{try{if(!window.claude||!claude.use)return;const s=await claude.use('sample');if(!s)return;const l=await s.limits().catch(()=>null);if(l&&l.images){AIS=s;aiImg=true;const m=document.getElementById('modal');if(A.S.sheet==='scan'&&st.mode==='sym'&&m)render(m)}}catch(_){}})();
function toBlob(img){return new Promise(ok=>{const s=Math.min(1,1280/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height)),c=document.createElement('canvas');c.width=Math.round((img.naturalWidth||img.width)*s);c.height=Math.round((img.naturalHeight||img.height)*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>ok(b),'image/jpeg',.88)})}
async function runAIVet(m){const h=st.h;if(!h||!AIS)return;h.ai={busy:true};render(m);
 const DZL=window.DZ.map(d=>`${d.id}: ${d.n} (signs: ${(d.signs||[]).join('; ')})`).join('\n');const sp=h.sp&&A.BY[h.sp];
 const beh=BEH.filter(b=>h.beh[b[0]]).map(b=>b[1]);const seen=(h.an&&h.an.F||[]).map(f=>f.l);
 const prompt=`You are an experienced aquarium fish vet. Look carefully at the attached photo of an aquarium animal and assess its health from what is VISIBLE.
Check: eyes (clear and dark vs cloudy, white, bulging), skin and scales (white spots, gold dust, fuzzy/cotton patches, red streaks, sores, raised pinecone scales, missing scales), fins (torn, ragged, clamped, red edges), gills, mouth, body shape (bloated, thin, bent spine), colour (faded or patchy), and anything abnormal.
${sp?`On-device recogniser guess: ${sp.n}.`:''}
On-device scanner flagged: ${seen.length?seen.join('; '):'nothing'}.
Owner reports: ${beh.length?beh.join('; '):'no behaviour problems ticked'}.
Choose likely conditions ONLY from this list (use the id), or use "other" with a short name:
${DZL}
Reply with ONLY one JSON object, no markdown:
{"is_fish":true,"species_guess":"","healthy":false,"score":0,"summary":"one or two plain sentences","signs":["what you see, where"],"likely":[{"id":"","name":"","confidence":0.0,"why":""}],"actions":["first steps, most important first, max 5"],"urgency":"low|medium|high","see_vet":false}
score: 100 = clearly healthy, below 50 = clearly sick. Be honest about uncertainty; if the photo is unclear say so in summary.`;
 try{const blob=await toBlob(h.img);const r=await AIS.json(prompt,{images:[blob],modelTier:'default'});h.ai=r&&typeof r==='object'?r:{err:'The AI answer could not be read. Try again.'};try{A.xp(10,'AI vet check');}catch(_){}}
 catch(e){h.ai={err:e&&e.code==='not_granted'?'AI check was not allowed. You can allow it next time you tap the button.':e&&e.code==='rate_limited'?'Too many checks right now. Try again in a minute.':'The AI check could not run right now. Try again later.'}}
 if(A.S.sheet==='scan')render(m)}
function aiBlock(){const h=st.h;if(!h||!h.an||!aiImg)return '';const a=h.ai;
 if(!a)return `<div class="aivet"><div class="aivh"><span class="aivic">${I('sparkle',20)}</span><div><b>AI vet check</b><small>A deeper look by Claude’s vision model: eyes, skin, fins, gills and body. Takes about 20 seconds.</small></div></div><button class="btn grad block" data-sc="aivet">${I('sparkle',16)}Run AI vet check</button></div>`;
 if(a.busy)return `<div class="aivet"><div class="aivh"><span class="aivic spin">${I('sparkle',20)}</span><div><b>AI vet is examining your fish…</b><small>Checking eyes, skin, fins, gills and body shape</small></div></div></div>`;
 if(a.err)return `<div class="aivet"><p class="sm" style="margin:0">${esc(a.err)}</p><button class="btn ghost sm" data-sc="aivet" style="margin-top:8px;color:#fff">${I('refresh',14)}Try again</button></div>`;
 if(a.is_fish===false)return `<div class="aivet"><b>The AI could not find a fish in this photo.</b><p class="sm" style="margin:6px 0 0">${esc(a.summary||'Try a closer, side-on photo of one fish.')}</p></div>`;
 const s=Math.max(0,Math.min(100,Math.round(+a.score||0))),c=s>=80?'#22C55E':s>=55?'#F59E0B':'#EF4444',DZB=Object.fromEntries(window.DZ.map(d=>[d.id,d]));
 return `<div class="aivet done" style="--hc:${c}"><div class="aivh"><span class="aivic">${I('sparkle',20)}</span><div><b>AI vet check</b><small>${esc(a.species_guess||'')}${a.urgency?` · urgency: ${esc(a.urgency)}`:''}</small></div><span class="aisc"><b>${s}</b>/100</span></div>
 <p class="aisum">${esc(a.summary||'')}</p>
 ${(a.signs||[]).length?`<div class="ailab">What it sees</div><ul class="aisg">${a.signs.slice(0,6).map(x=>`<li>${esc(String(x))}</li>`).join('')}</ul>`:''}
 ${(a.likely||[]).length?`<div class="ailab">Most likely</div>${a.likely.slice(0,3).map(l=>{const d=DZB[l.id];return `<button class="hdz" ${d?`data-open="${d.id}"`:''}><span class="hdzn"><b>${esc(d?d.n:(l.name||l.id))}</b><small>${Math.round((+l.confidence||0)*100)}% · ${esc(l.why||'')}</small></span>${d?I('chev',16):''}</button>`}).join('')}`:''}
 ${(a.actions||[]).length?`<div class="ailab">Do this now</div><ol class="hfa">${a.actions.slice(0,5).map(x=>`<li>${esc(String(x))}</li>`).join('')}</ol>`:''}
 ${a.see_vet?`<p class="xs hwarn">${I('alert',13)} Consider asking a fish vet or experienced keeper.</p>`:''}</div>`}
function healthStart(){return `<div class="res hstart"><div class="hhero"><span class="hhic">${I('virus',28)}</span><div><h3>Is my fish healthy?</h3><p>Take a clear side photo of one fish. The scanner looks for visible warning signs, asks 6 quick questions, then gives a health score, the likely problem and what to do right now.</p></div></div>
 <div class="hsteps"><span><b>1</b>Photo</span><i></i><span><b>2</b>AI checks signs</span><i></i><span><b>3</b>Quick questions</span><i></i><span><b>4</b>Score & first aid</span></div>
 <div class="hbtns"><button class="btn grad" data-sc="hsnap">${I('camera',18)}Take a photo</button><button class="btn ghost" data-sc="hgal" style="color:#fff">${I('image',18)}Choose a photo</button></div>
 <ul class="hlook"><li>${I('check',14)}White spots and cotton-like patches</li><li>${I('check',14)}Unusual redness or faded colours for that species</li><li>${I('check',14)}Your answers about breathing, eating and swimming</li></ul>
 <button class="hman" data-sc="hmanual">${I('layers',15)}No photo? Pick the signs you see instead</button>
 <p class="xs hdisc">${I('info',12)} A quick visual check, not a vet diagnosis. Always test your water too.</p></div>`}
function manualSigns(){const S=window.SYM,sel=st.sym,NF={skinpeel:'frog',gillcurl:'axolotl',floating:'axolotl',swollenlids:'turtle',nosebubble:'turtle',softshell:'turtle',whitering:'shrimp',headworms:'shrimp',greengrowth:'shrimp',shellrot:'turtle'};const E=Object.entries(S),btn=([k,l])=>`<button class="sym" data-sym="${k}" aria-pressed="${sel.includes(k)}"><svg viewBox="-10 -20 260 160">${D.fish('community',{c1:'#7FB3D5',sym:[k]})}</svg>${esc(l)}</button>`,nb=([k,l])=>`<button class="sym symtx" data-sym="${k}" aria-pressed="${sel.includes(k)}"><b>${{frog:'Frog / newt',axolotl:'Axolotl',turtle:'Turtle',shrimp:'Shrimp'}[NF[k]]}</b>${esc(l.replace(/ \((frogs, newts|axolotl|turtle|shrimp)\)$/,''))}</button>`;return `<div class="symgrid">${E.filter(([k])=>!NF[k]).map(btn).join('')}</div><h4 class="symh">Shrimp, frogs, axolotls &amp; turtles</h4><div class="symgrid">${E.filter(([k])=>NF[k]).map(nb).join('')}</div>`}
function healthView(){const h=st.h;
 if(st.hmanual&&!h)return `<div class="res"><button class="hback" data-sc="hagain">${I('back',15)}Back</button><h3 style="font-size:19px;margin-top:8px">What do you see?</h3><p class="sm muted" style="margin:4px 0 12px">Tap every sign that matches.</p>${manualSigns()}</div>${st.sym.length?resultBlock():''}`;
 if(!h)return healthStart();
 if(h.busy)return `<div class="res hbusy"><div class="himg"><img src="${h.img.src}" alt=""><span class="hscanline"></span></div><b>Checking your fish…</b><span class="sm muted">Looking for spots, patches, redness and colour changes</span></div>`;
 if(h.nofish)return `<div class="res nofish"><div class="himg"><img src="${h.img.src}" alt=""></div><span class="nfic">${I('search',26)}</span><div class="nft"><b>No fish found</b><span>We couldn't see a fish or aquarium animal in this photo, so we can't check its health. Take a clear side photo of one fish.</span></div><div class="nfb"><button class="btn sm grad" data-sc="hagain">${I('camera',15)}Try another photo</button><button class="btn sm ghost" data-sc="hforce">Check anyway</button></div></div>`;
 if(h.err)return `<div class="res"><p>${esc(h.err)}</p><button class="btn grad" data-sc="hagain">Try again</button></div>`;
 const sp=h.sp&&A.BY[h.sp],F=h.an.F;
 const s0=(h.ai&&h.ai.score!=null&&!h.ai.err&&!h.ai.busy)?Math.round(+h.ai.score):healthScore(),c0=s0>=80?'#22C55E':s0>=55?'#F59E0B':'#EF4444';return `<div class="res"><div class="himg"><img src="${h.an.overlay}" alt="Your fish with marked areas"><span class="hbadge" style="--hc:${c0}"><b>${s0}</b>/100 · ${s0>=80?'Looks healthy':s0>=55?'Watch closely':'Act now'}</span></div>
 <div class="hsp">${sp?`<span>Looks like a <b>${esc(sp.n)}</b></span><button class="lnk" data-open="${sp.id}">Care guide ${I('chev',13)}</button>`:'<span>Species not recognised. The check still works.</span>'}</div>
 ${h.an.qual?`<p class="xs hwarn">${I('alert',13)} ${h.an.qual}</p>`:''}
 <h3 class="hh3">${I('eye',17)} What the scanner saw</h3>${F.length?F.map(f=>`<div class="hfind s${f.sev}"><i style="background:${f.col}"></i><span><b>${esc(f.l)}</b>${f.maybe?'<small>Possible, so check closely</small>':''}</span></div>`).join(''):`<div class="hfind ok">${I('check',16)}<span><b>No visible warning signs found</b><small>No spots, patches, unusual redness or faded colour detected.</small></span></div>`}
 <h3 class="hh3">${I('heart',17)} Quick questions</h3><div class="hbeh">${BEH.map(([k,l])=>`<button class="${h.beh[k]?'on':''}" data-sc="hbeh:${k}">${h.beh[k]?I('check',14):''}${esc(l)}</button>`).join('')}</div>
 ${aiBlock()}<details class="hmore"><summary>${I('plus',14)} Add other signs you can see</summary>${manualSigns()}</details></div>${resultBlock()}`}
function resultBlock(){const _ai=st.h&&st.h.ai&&st.h.ai.score!=null&&!st.h.ai.err&&!st.h.ai.busy;const s=_ai?Math.max(0,Math.min(100,Math.round(+st.h.ai.score))):st.h&&st.h.an?healthScore():sevCap(Math.max(5,100-st.sym.length*12)),keys=healthKeys(),dz=_ai&&(st.h.ai.likely||[]).length?(st.h.ai.likely.map(l=>[window.DZ.find(d=>d.id===l.id),+l.confidence||.5]).filter(x=>x[0]).concat(rankDz(keys)).filter((x,i,arr)=>arr.findIndex(y=>y[0].id===x[0].id)===i).slice(0,3)):rankDz(keys);const lvl=s>=80?['Looks healthy','#22C55E','Keep doing what you’re doing. Check again if behaviour changes.']:s>=55?['Keep an eye on it','#F59E0B','Some signs need watching. Test your water today.']:['Likely unwell, act now','#EF4444','Follow the first steps below and start treatment.'];
 const first=dz.length?String(dz[0][0].treat||'').split(/(?<=\.)\s+/).filter(Boolean).slice(0,2):[];
 return `<div class="res hresult"><div class="hscore" style="--hc:${lvl[1]}"><div class="hring" style="--p:${s}"><b>${s}</b><small>/100</small></div><div><b class="hlvl">${lvl[0]}</b><p>${lvl[2]}</p></div></div>
 ${dz.length?`<h3 class="hh3">${I('virus',17)} Most likely</h3>${dz.map(([d,v],k)=>`<button class="hdz" data-open="${d.id}"><span class="hdzn"><b>${esc(d.n)}</b><small>${['','Mild','Serious','Urgent'][d.sev]} · ${Math.min(95,Math.round(v*100))}% match</small></span>${k===0?'<em>Top match</em>':''}${I('chev',16)}</button>`).join('')}`:''}
 <h3 class="hh3">${I('check',17)} Do this now</h3><ol class="hfa">${(first.length?first.map(t=>esc(t)):[]).concat(['Test ammonia, nitrite, nitrate and temperature today.','Do a 25–30% water change with dechlorinated water at the same temperature.','If possible, move the sick fish to a quarantine tank.']).slice(0,5).map(t=>`<li>${t}</li>`).join('')}</ol>
 ${dz.length&&dz[0][0].meds&&dz[0][0].meds.length?`<div class="hmeds"><span class="xs">Treatments</span>${dz[0][0].meds.slice(0,4).map(id=>A.BY[id]?`<button data-open="${id}">${esc(A.BY[id].n)}</button>`:'').join('')}</div>`:''}
 <div class="hacts"><button class="btn sm grad" data-sc="hsave">${I('tank',15)}Save to tank log</button><button class="btn sm ghost" style="color:#fff" data-sc="hask">${I('chat',15)}Ask the community</button><button class="btn sm ghost" style="color:#fff" data-sc="hagain">${I('refresh',15)}New check</button></div>
 <p class="xs hdisc">${I('info',12)} A quick visual check, not a vet diagnosis.</p></div>`}

function symView(){const S=window.SYM,DZ=window.DZ,sel=st.sym;const ranked=sel.length?DZ.map(d=>{const hit=d.sym.filter(s=>sel.includes(s)).length;return[d,hit?hit/Math.sqrt(d.sym.length*sel.length)+d.sev*.01:0]}).filter(a=>a[1]>0).sort((a,b)=>b[1]-a[1]).slice(0,4):[];
 return `<div class="res"><h3 style="font-size:19px">What do you see?</h3><p class="sm muted" style="margin:4px 0 12px">Tap every sign that matches. Pictures show what to look for.</p><div class="symgrid">${Object.entries(S).map(([k,l])=>`<button class="sym" data-sym="${k}" aria-pressed="${sel.includes(k)}"><svg viewBox="-10 -20 260 160">${D.fish('community',{c1:'#7FB3D5',sym:[k]})}</svg>${esc(l)}</button>`).join('')}</div></div>
 ${sel.length?`<div class="res"><h3 style="font-size:19px;margin-bottom:10px">Possible causes</h3>${ranked.length?ranked.map(([d,s],k)=>`<button class="prow" data-open="${d.id}" style="background:#10313C;border-color:#1C4351;color:#EAF7F5;text-align:left;width:100%;margin-bottom:8px"><span class="th" style="background:#0B2630">${I('virus',20)}</span><span><b>${k===0?'Most likely: ':''}${esc(d.n)}</b><br><span class="xs" style="color:#93B6B1">${esc(d.signs[0])}</span></span><span class="pill ${['','info','warn','bad'][d.sev]}">${['','Mild','Serious','Urgent'][d.sev]}</span></button>`).join(''):'<p class="muted">No single match. Test your water first: most sickness starts with ammonia or nitrite.</p>'}
 <p class="xs muted" style="margin-top:6px">Guidance only, not a veterinary diagnosis. Test ammonia, nitrite and nitrate before medicating.</p></div>`:''}`}

const dev=()=>{const coarse=matchMedia('(pointer:coarse)').matches;if(!coarse)return 'desktop';return Math.min(innerWidth,innerHeight)>=700?'tablet':'mobile'};
const TIPS=[['sun','Turn on the tank light, room lights off'],['eye','Side-on: let the fish fill the frame'],['wave','Hold the lens flat against the glass'],['clock','Wait until the fish stops moving']];
let loop=null,hist=[],tipI=0,seen=new Set();
function frameCanvas(v){const c=document.createElement('canvas');const w=v.videoWidth,h=v.videoHeight,s=Math.min(w,h)*.86;c.width=c.height=Math.round(s);c.getContext('2d').drawImage(v,(w-s)/2,(h-s)/2,s,s,0,0,c.width,c.height);c.naturalWidth=c.width;c.naturalHeight=c.height;return c}
function qQuick(c){const W=96,H=96,t=document.createElement('canvas');t.width=W;t.height=H;const g=t.getContext('2d');g.drawImage(c,0,0,W,H);const d=g.getImageData(0,0,W,H).data;let sum=0,lap=0,n=0;const gr=new Float32Array(W*H);for(let i=0;i<W*H;i++){const v=.299*d[i*4]+.587*d[i*4+1]+.114*d[i*4+2];gr[i]=v;sum+=v}const mean=sum/(W*H);for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++){const i=y*W+x,l=4*gr[i]-gr[i-1]-gr[i+1]-gr[i-W]-gr[i+W];lap+=l*l;n++}const sharp=lap/n;
 if(mean<40)return{ok:false,msg:'Too dark: turn on the tank light'};if(mean>230)return{ok:false,msg:'Too bright: avoid glare'};if(sharp<35)return{ok:false,msg:'Hold steady…'};return{ok:true}}
function statusHtml(){const L=st.live,t=L&&L.top[0],x=t&&A.BY[t.id];
 if(st.img&&st.busy)return `<span class="dot busy"></span><b>Identifying…</b>`;
 if(st.img&&st.res){const r=st.res.top[0];return `<span class="dot ok"></span><b>${esc(A.BY[r.id].n)}</b><em>${Math.round(r.p*100)}%</em>`}
 if(!st.stream)return `<span class="dot"></span><b>Camera off</b>`;
 if(!model)return `<span class="dot busy"></span><b>Loading AI scanner…</b>`;
 if(x&&st.lockId===t.id)return `<span class="dot ok"></span><b>${esc(x.n)}</b><em>${Math.round(t.p*100)}%</em>`;
 return `<span class="dot scan"></span><b>${esc(st.hint||'Looking for a fish…')}</b>`}
function unknownHtml(r,live){return `<div class="${live?'lvres':'res'} nofish"><span class="nfic">${I('search',26)}</span><div class="nft"><b>I can't recognise this fish</b><span>It doesn't match any fish I know well enough to name it. Try a sharper, side-on photo of one fish with the tank light on, or search by name.</span></div><div class="nfb"><button class="btn sm grad" data-sc="again">${I('camera',15)}Try again</button><button class="btn sm ghost" data-sc="nonematch">${I('search',15)}Search by name</button></div><button class="lnk xs scnot" data-sc="showpick">Show closest look-alikes (not a match)</button></div>`}
function pickHtml(r,live){const C=r.top.slice(0,6);return `<div class="${live?'lvres':'res'} scpick"><div class="scph">${r.known===false?`<b>${I('search',16)} Closest look-alikes</b><span>These are NOT a confident match. Only tap one if it really is your fish.</span>`:`<b>${I('search',16)} Which one is it?</b><span>We're not sure. Compare your fish with these and tap the right one.</span>`}</div><div class="scpg">${C.map((o,i)=>{const y=A.BY[o.id];const ph=!D.hasIll(y.id)&&window.SCANPH&&SCANPH[y.id];return `<button class="scpc${i===0?' top':''}" data-scpick="${y.id}"><span class="scpi${ph?' photo':''}"><img src="${ph?ph.src:D.src(y.id)}" alt="" loading="lazy">${ph?`<em title="${esc(ph.cr)}">${esc(ph.cr.split(',')[0])}</em>`:''}</span><b>${esc(y.n)}</b><small>${i===0?'Closest match':'Possible'}</small></button>`}).join('')}</div><div class="scpf"><button class="btn sm ghost" data-sc="again">${I('camera',15)}Try another photo</button><button class="btn sm ghost" data-sc="nonematch">${I('search',15)}None of these</button></div><p class="xs scpt">${I('info',13)} Tip: fill the frame with the whole fish, side on, with the tank light on.</p></div>`}
function pickedCard(r,live){const x=A.BY[st.picked];return `<div class="${live?'lvres':'res'}"><div style="display:flex;gap:12px;align-items:center"><span class="scok">${I('check',22,3)}</span><div class="lvn" style="min-width:0"><span class="xs">You picked</span><b>${esc(x.n)}</b><i>${esc(x.sci||'')}</i></div><img src="${D.src(x.id)}" alt="" style="width:84px;height:56px;object-fit:contain;margin-left:auto"></div><div class="lvbtns" style="margin-top:10px"><button class="btn sm grad" data-open="${x.id}">${I('book',15)}Profile</button><button class="btn sm ghost" data-addplan="${x.id}">${I('plus',15)}Add</button><button class="btn sm ghost" data-sc="sym">${I('virus',15)}Health</button></div><button class="lnk xs" data-sc="showpick" style="margin-top:8px">Change my choice</button></div>`}
function liveCard(){const r=st.img?st.res:(st.lockId&&st.live);if(!r)return '';if(st.img&&r.fish<NOFISH&&!st.nfShow)return noFishHtml(true);if(st.picked&&A.BY[st.picked])return pickedCard(r,true);if(r.known===false&&!st.showPick)return unknownHtml(r,true);if(!r.sure||st.showPick)return pickHtml(r,true);const t=r.top[0],x=A.BY[t.id];return `<div class="lvres">${ring(t.p)}<div class="lvn"><span class="xs">${t.p<.4?'Best guess':'Identified'}</span><b>${esc(x.n)}</b><i>${esc(x.sci)}</i></div><img src="${D.src(x.id)}" alt="">
 <div class="lvbtns"><button class="btn sm grad" data-open="${x.id}">${I('book',15)}Profile</button><button class="btn sm ghost" data-addplan="${x.id}">${I('plus',15)}Add</button><button class="btn sm ghost" data-sc="sym">${I('virus',15)}Health</button></div>
 <button class="lnk xs scnot" data-sc="showpick">Not right? Compare with similar fish</button></div>`}
function paintLive(m){const s=m.querySelector('.lvstatus');if(s)s.innerHTML=statusHtml();const c=m.querySelector('.lvrcard');if(c)c.innerHTML=liveCard();const r=m.querySelector('.reticle');if(r)r.classList.toggle('lock',!!(st.lockId&&!st.img)||!!(st.img&&st.res&&!(st.res.fish<NOFISH)))}
function plat(){const u=navigator.userAgent,ios=/iPhone|iPad|iPod/.test(u)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1),and=/Android/.test(u);
 const br=/CriOS|Chrome/.test(u)&&!/Edg/.test(u)?'chrome':/FxiOS|Firefox/.test(u)?'firefox':/Edg/.test(u)?'edge':/Safari/.test(u)?'safari':'other';return{ios,and,br,frame:window.self!==window.top}}
function hostBlocks(){try{const pp=document.permissionsPolicy||document.featurePolicy;if(pp&&pp.allowsFeature&&!pp.allowsFeature('camera'))return true}catch(_){}return window.self!==window.top&&(st.camErr==='NotAllowedError'||st.camErr==='SecurityError'||st.camErr==='NoAPI')}
function camSteps(){const p=plat();
 if(p.ios&&p.br==='safari')return ['Tap <b>aA</b> on the left of the Safari address bar.','Tap <b>Website Settings</b>.','Set <b>Camera</b> to <b>Allow</b> (or <b>Ask</b>).','Tap <b>Try again</b> below.'];
 if(p.ios)return ['Open the iPhone <b>Settings</b> app.',`Tap <b>Apps</b> (iOS 18) and choose <b>${p.br==='chrome'?'Chrome':p.br==='firefox'?'Firefox':'your browser'}</b>.`,'Turn <b>Camera</b> on.','Come back and tap <b>Try again</b>.'];
 if(p.and)return ['Tap the <b>settings icon</b> left of the web address.','Tap <b>Permissions</b> → <b>Camera</b> → <b>Allow</b>.','Tap <b>Try again</b> below.'];
 if(p.br==='safari')return ['Menu bar: <b>Safari</b> → <b>Settings for This Website</b>.','Set <b>Camera</b> to <b>Allow</b>.','Click <b>Try again</b>.'];
 return ['Click the <b>icon left of the web address</b>.','Set <b>Camera</b> to <b>Allow</b>.','Click <b>Try again</b>.']}
function blockedPanel(){const p=plat(),noCam=st.camErr==='NotFoundError'||st.camErr==='OverconstrainedError',busy=st.camErr==='NotReadableError',host=hostBlocks();
 if(host)return `<div class="lvoff blocked host"><span class="lvbic">${I('camera',30)}</span><b>Take a photo to identify</b><span>You’re viewing TankMates inside another app, and that app doesn’t give websites the live camera. No setting can change that here, so you don’t need to do anything.</span>
 <div class="lvbbtns"><button class="btn grad" data-sc="snapnative">${I('camera',18)}Take a photo</button><button class="btn ghost" data-sc="gal">${I('image',17)}Choose photo</button></div>
 <div class="lvhow2">${I('info',14)}<span>The AI identifies the fish from a photo just as well. <b>Live scanning</b> (point and it recognises by itself) works when you open TankMates on its own website in Safari or Chrome and tap <b>Allow</b> when asked.</span></div></div>`;
 const title=noCam?'No camera found':busy?'Your camera is busy':'Camera access is blocked';
 const sub=noCam?'Take or choose a photo instead.':busy?'Close other apps using the camera, then try again, or take a photo.':'You chose not to allow the camera for this site. Allow it once and live scanning starts, or just take a photo.';
 return `<div class="lvoff blocked"><span class="lvbic">${I('camera',30)}</span><b>${title}</b><span>${sub}</span>
 <div class="lvbbtns"><button class="btn grad" data-sc="snapnative">${I('camera',18)}Take a photo</button><button class="btn ghost" data-sc="cam">${I('refresh',17)}Try again</button></div>
 ${!noCam&&!busy?`<div class="lvhow"><b>${I('info',15)} Allow the camera on ${p.ios?(p.br==='safari'?'iPhone Safari':'iPhone '+(p.br==='chrome'?'Chrome':'browser')):p.and?'Android':'this browser'}</b><ol>${camSteps().map(s=>`<li>${s}</li>`).join('')}</ol></div>`:''}</div>`}
function liveView(){const d=dev(),ti=TIPS[tipI%TIPS.length];return `<div class="lv">
 ${st.img?`<img class="lvmedia" src="${st.img.src}" alt="Your photo">`:st.stream?`<video id="camv" class="lvmedia" autoplay playsinline muted></video>`:(st.denied?blockedPanel():`<div class="lvoff">${CI('camera','#38E1C6',64)}<b>Starting camera…</b><span>Point at a fish to identify it.</span></div>`)}
 <div class="lvshade"></div>
 <div class="lvtop"><button class="lvic" data-sclose aria-label="Close">${I('x',22)}</button><div class="lvseg"><button data-sc="mode-cam" aria-pressed="true">${I('scan',15)}Identify</button><button data-sc="mode-sym" aria-pressed="false">${I('virus',15)}Health</button><button data-sc="mode-tank" aria-pressed="false">${I('tank',15)}Tank</button></div><button class="lvic ${st.torch?'on':''}" data-sc="torch" aria-label="Torch" ${st.stream&&st.canTorch?'':'style="visibility:hidden"'}>${I('bulb',20)}</button></div>
 <div class="reticle"><i class="tl"></i><i class="tr"></i><i class="bl"></i><i class="br2"></i>${st.stream&&!st.img&&st.auto?'<span class="scanl"></span>':''}</div>
 <div class="lvstatus">${statusHtml()}</div>
 <div class="lvsheet"><div class="lvrcard">${liveCard()}</div>
  <div class="lvctl"><button class="lvside" data-sc="gal" aria-label="Pick from gallery">${I('image',22)}<span>Gallery</span></button>
  ${st.img?`<button class="shut2 again" data-sc="again" aria-label="Scan again">${I('refresh',28)}</button>`:`<button class="shut2" data-sc="${st.stream?'snap':'snapnative'}" aria-label="Take photo"><span></span></button>`}
  <button class="lvside ${st.auto?'on':''}" data-sc="auto" aria-pressed="${!!st.auto}">${I('sparkle',22)}<span>Auto ${st.auto?'on':'off'}</span></button></div>
  <p class="lvtip">${I(ti[0],14)}${ti[1]}</p>
  <p class="lvfine">AI runs on your device · nothing is uploaded</p></div>
 <input id="scf" type="file" accept="image/*" capture="environment" hidden><input id="scg" type="file" accept="image/*" hidden></div>`}
function deskView(){const q=st.q;return `<div class="dsk"><div class="dzwrap">
 ${st.img?`<div class="dzimg"><img src="${st.img.src}" alt="Your photo"><div class="reticle ${st.res?'lock':''}"><i class="tl"></i><i class="tr"></i><i class="bl"></i><i class="br2"></i>${st.busy?'<span class="scanl"></span>':''}</div></div>
  ${q?`<div class="qual">${[[q.okB,q.okB?'Good light':q.bright<=45?'Too dark':'Too bright'],[q.okS,q.okS?'Sharp':'Blurry'],[q.okR,q.okR?'Good resolution':'Low resolution']].map(([ok,t])=>`<span class="${ok?'ok':'no'}">${I(ok?'check':'alert',14)}${t}</span>`).join('')}</div>`:''}
  <div class="dzact"><button class="btn ghost" data-sc="again">${I('refresh',16)}Try another photo</button><button class="btn ghost" data-sc="gal">${I('image',16)}Choose file</button></div>`
 :st.stream?`<div class="dzimg"><video id="camv" autoplay playsinline muted></video><div class="reticle"><i class="tl"></i><i class="tr"></i><i class="bl"></i><i class="br2"></i></div></div><div class="dzact"><button class="btn grad" data-sc="snap">${I('camera',16)}Capture</button><button class="btn ghost" data-sc="again">${I('x',16)}Stop webcam</button></div>`
 :`<label class="dz" id="dz" for="scg"><span class="dzic">${I('upload',34)}</span><b>Drop a fish photo here</b><span>or <u>browse your files</u> · or paste with Ctrl/⌘ + V</span><span class="dzfmt">JPG, PNG, WEBP or HEIC · side-on photo · fish fills most of the frame</span></label>
  <div class="dzact"><button class="btn grad" data-sc="gal">${I('image',16)}Choose photo</button><button class="btn ghost" data-sc="cam">${I('camera',16)}Use webcam</button></div>${st.denied?`<p class="camerr" role="alert">${I('alert',15)}${st.camErr==='NotFoundError'||st.camErr==='OverconstrainedError'?'No webcam found on this computer. Choose or drop a photo instead.':st.camErr==='NotReadableError'?'Your webcam is being used by another app. Close it and try again, or choose a photo.':st.camErr==='NoAPI'?'This browser can’t use the webcam here. Choose or drop a photo instead.':'Webcam access is blocked. Allow the camera in your browser’s address bar, or choose a photo.'}</p>`:''}`}
 </div><div class="dres">${st.err?`<div class="res"><b style="color:#FF6A57">${esc(st.err)}</b></div>`:st.res?resView():st.busy?`<div class="dempty"><span class="spin"></span><b>Identifying on your device…</b></div>`:`<div class="dempty"><span class="aib">${I('sparkle',14)}Powered by AI</span><h3>Identify any fish from a photo</h3><ol><li><b>1</b>Upload a clear, side-on photo</li><li><b>2</b>AI compares it with ${window.SP.length} species</li><li><b>3</b>Open the profile or check its health</li></ol><div class="dtips">${TIPS.map(([i,t])=>`<span>${I(i,15)}${t}</span>`).join('')}</div><p class="xs" style="color:#93B6B1">Runs on your computer. Nothing is uploaded.</p></div>`}</div></div>
 <input id="scf" type="file" accept="image/*" hidden><input id="scg" type="file" accept="image/*" hidden>`}
function render(m){const sym=st.mode==='sym',tk=st.mode==='tank',d=dev();
 if(!sym&&!tk&&d!=='desktop'){m.innerHTML=`<div class="cam sc3 dev-${d}" role="dialog" aria-modal="true" aria-label="Fish scanner">${liveView()}</div>`}
 else m.innerHTML=`<div class="cam sc3 dev-${d} ${sym||tk?'symmode':''} ${tk?'tankmode':''}" role="dialog" aria-modal="true" aria-label="Fish scanner"><div class="top"><button class="close" data-sclose aria-label="Close">${I('x',20)}</button><div class="seg" style="background:#10313C"><button data-sc="mode-cam" aria-pressed="${!sym&&!tk}" style="color:#fff">${I('scan',15)} Identify</button><button data-sc="mode-sym" aria-pressed="${sym}" style="color:#fff">${I('virus',15)} Health</button><button data-sc="mode-tank" aria-pressed="${tk}" style="color:#fff">${I('tank',15)} Tank check</button></div><span style="width:40px"></span></div><div class="body">${tk?tankView():sym?healthView():deskView()}</div>${sym?'<input id="hcf" type="file" accept="image/*" capture="environment" hidden><input id="hcg" type="file" accept="image/*" hidden>':''}</div>`;
 const v=m.querySelector('#camv');if(v&&st.stream)v.srcObject=st.stream;
 const onFile=e=>{const f=e.target.files[0];if(!f)return;loadFile(f,m)};
 m.querySelector('#scf')?.addEventListener('change',onFile);m.querySelector('#scg')?.addEventListener('change',onFile);const onH=e=>{const f=e.target.files[0];if(!f)return;const im=new Image();im.onload=()=>runHealth(im,m);im.onerror=()=>badFile(m);im.src=URL.createObjectURL(f)};m.querySelector('#hcf')?.addEventListener('change',onH);m.querySelector('#hcg')?.addEventListener('change',onH);
 const dz=m.querySelector('#dz');if(dz){['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('over')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('over')}));dz.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f&&f.type.startsWith('image/'))loadFile(f,m)})}}
function badFile(m){stopLoop();st.img=null;st.res=null;st.q=null;st.busy=false;st.err='That file could not be opened as a photo. Try a JPG or PNG image.';render(m);try{A.toast&&A.toast('That file is not a readable photo')}catch(_){}}
function loadFile(f,m){if(f.type&&!/^image\//.test(f.type)){badFile(m);return}const img=new Image();img.onload=()=>{st.err=null;run(img,m)};img.onerror=()=>badFile(m);img.src=URL.createObjectURL(f)}
async function run(img,m){stopLoop();if(st.stream&&dev()==='desktop')stop(true);st.img=img;st.q=quality(img);st.res=null;st.err=null;st.busy=true;render(m);
 try{st.nfShow=false;st.res=await identify(img);if(st.res.fish>=NOFISH){A.stat('scans');A.xp(15,'Fish scanned');A.award('scan1')}else{try{A.SFX&&A.SFX('warn')}catch(_){}}}catch(e){st.err=e.message||'Scanner failed to load. Check your connection once so the engine can be cached.'}st.busy=false;if(A.S.sheet==='scan'){render(m);paintLive(m)}}
async function startCam(m){try{st.denied=false;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw {name:'NoAPI'};st.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1920},height:{ideal:1440}},audio:false});
 try{const tr=st.stream.getVideoTracks()[0],cap=tr.getCapabilities?tr.getCapabilities():{};st.canTorch=!!cap.torch}catch(_){}render(m);if(dev()!=='desktop')startLoop(m)}catch(e){st.denied=true;st.camErr=(e&&e.name)||'Error';st.stream=null;render(m)}}
function stopLoop(){if(loop){clearInterval(loop);loop=null}}
function startLoop(m){stopLoop();hist=[];let tick=0;loop=setInterval(async()=>{if(A.S.sheet!=='scan'){stopLoop();return}tick++;if(tick%6===0){tipI++;const tp=m.querySelector('.lvtip');const ti=TIPS[tipI%TIPS.length];if(tp)tp.innerHTML=I(ti[0],14)+ti[1]}
 if(st.busy||!st.stream||st.img||!st.auto)return;const v=m.querySelector('#camv');if(!v||v.readyState<2||!v.videoWidth)return;if(!model||!ref){paintLive(m);return}
 st.busy=true;try{const c=frameCanvas(v),q=qQuick(c);if(!q.ok){st.hint=q.msg;hist=[]}else{const r=await identify(c,true),t=r.top[0];hist.push(t.id);hist=hist.slice(-3);const stable=hist.length>=2&&hist[hist.length-1]===hist[hist.length-2];
  if(r.fish<LOCKFISH||!t){hist=[];st.lockId=null;st.hint=r.plant>.6?'That looks like a plant. Point the camera at a fish':'No fish in view. Point the camera at a fish'}else if(r.known===false){hist=[];st.lockId=null;st.hint='I can\'t recognise this fish yet. Get closer, side on'}else if(stable&&r.raw>.5){st.live=r;if(!r.sure){stopLoop();st.hint='Not sure — pick the right one below'}if(st.lockId!==t.id){st.lockId=t.id;try{navigator.vibrate&&navigator.vibrate(40)}catch(_){}A.SFX&&A.SFX('success');if(!seen.has(t.id)){seen.add(t.id);A.stat('scans');A.xp(15,'Fish identified');A.award('scan1')}}}
  else{st.hint=st.lockId?'Hold steady…':'Looking for a fish…';if(!stable&&st.lockId&&t.id!==st.lockId&&t.p>.5){st.lockId=null}}}}catch(e){st.hint='Scanner error: '+(e.message||'')}finally{st.busy=false;paintLive(m)}},850)}
function stop(keep){stopLoop();if(st.stream){st.stream.getTracks().forEach(t=>t.stop());st.stream=null}if(!keep){st={mode:st.mode,img:null,res:null,q:null,sym:st.sym,busy:false,err:null,stream:null,auto:st.auto,denied:false};hist=[]}}
document.addEventListener('click',e=>{const p=e.target.closest('[data-scpick]');if(!p||A.S.sheet!=='scan')return;e.preventDefault();const m=document.getElementById('modal');const r=st.img?st.res:st.live;st.picked=p.dataset.scpick;st.showPick=false;stopLoop();
 try{const L=JSON.parse(localStorage.getItem('tm3-scanfix')||'[]');L.unshift({at:Date.now(),guess:r&&r.top&&r.top[0]?r.top[0].id:null,picked:st.picked,raw:r?Math.round(r.raw*100)/100:null});localStorage.setItem('tm3-scanfix',JSON.stringify(L.slice(0,200)))}catch(_){}
 if(!seen.has(st.picked)){seen.add(st.picked);try{A.stat('scans');A.xp(15,'Fish identified');A.award('scan1')}catch(_){}}render(m);paintLive(m)},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-sc],[data-sym]');if(!b||A.S.sheet!=='scan')return;const m=document.getElementById('modal'),k=b.dataset.sc;
 if(b.dataset.sym){const s=b.dataset.sym,i=st.sym.indexOf(s);i>=0?st.sym.splice(i,1):st.sym.push(s);const y=m.querySelector('.body').scrollTop;render(m);m.querySelector('.body').scrollTop=y;return}
 if(k==='mode-cam'){st.mode='cam';render(m);if(dev()!=='desktop'&&!st.stream&&!st.img)startCam(m);else if(st.stream&&dev()!=='desktop')startLoop(m)}
 else if(k==='mode-tank'){stop(true);st.mode='tank';render(m)}
 else if(k==='mode-sym'||k==='sym'){stop(true);st.mode='sym';if(k==='sym'&&st.img){runHealth(st.img,m)}else render(m)}
 else if(k==='aivet'){runAIVet(m)}
 else if(k==='hsnap')m.querySelector('#hcf')?.click();else if(k==='hgal')m.querySelector('#hcg')?.click();
 else if(k==='hmanual'){st.hmanual=true;st.h=null;render(m)}else if(k==='hagain'){st.h=null;st.hmanual=false;st.sym=[];render(m)}
 else if(k&&k.startsWith('hbeh:')){const q=k.slice(5);st.h.beh[q]=!st.h.beh[q];const y=m.querySelector('.body').scrollTop;render(m);m.querySelector('.body').scrollTop=y}
 else if(k==='hsave'){const T=A.S.tanks.filter(t=>t.type!=='future');if(!T.length){A.toast('Add your aquarium in My tanks first, then save checks to its log');return}const t=T[0],s=st.h&&st.h.an?healthScore():null,dz=rankDz(healthKeys());(t.events=t.events||[]).push({date:new Date().toISOString().slice(0,10),type:'health',text:`Health check${st.h&&st.h.sp?' ('+A.BY[st.h.sp].n+')':''}: ${s!=null?s+'/100':''}${dz.length?' · likely '+dz[0][0].n:' · no warning signs'}`});A.saveTanks();A.toast(`Saved to ${t.name}’s log`)}
 else if(k==='hask'){const s=st.h&&st.h.an?healthScore():null,dz=rankDz(healthKeys()),sp=st.h&&st.h.sp&&A.BY[st.h.sp];const txt=`Health check: my ${sp?sp.n:'fish'}${dz.length?' might have '+dz[0][0].n:''}${s!=null?' (score '+s+'/100)':''}. Signs: ${healthKeys().map(x=>window.SYM[x]||x).join(', ')||'none visible'}. Any advice?`;stop();A.closeSheet();A.S.view='community';A.S.cm.user=null;A.S.cm.post=null;A.S.cm.sec='rooms';A.S.cm.room='help';A.render();setTimeout(()=>{const i=document.querySelector('[data-hform="r:help"] input');if(i){i.value=txt;i.focus()}},250)}
 else if(k==='cam'){ensure().catch(()=>{});startCam(m)}else if(k==='snapnative'){const f=m.querySelector('#scf');if(f){f.setAttribute('capture','environment');f.click()}}else if(k==='openbrowser'){try{window.open(location.href.split('#')[0]+'#scan','_blank','noopener')}catch(_){}}else if(k==='copylink'){navigator.clipboard?.writeText(location.href.split('#')[0]).then(()=>A.toast&&A.toast('Link copied — paste it in Safari or Chrome'),()=>{})}else if(k==='gal')m.querySelector('#scg').click();
 else if(k==='nfguess'){st.nfShow=true;render(m)}
 else if(k==='showpick'){st.picked=null;st.showPick=true;stopLoop();render(m)}
 else if(k==='nonematch'){try{stop()}catch(_){}A.S.sheet=null;try{A.go('explore',{q:''})}catch(_){location.hash='explore'}setTimeout(()=>{const i=document.querySelector('#xq,#hsearch,.searchin input');if(i){i.focus()}},400);try{A.toast&&A.toast('Search all species by name')}catch(_){}}
 else if(k==='hforce'){if(st.h&&st.h.img){const im=st.h.img;st.h={img:im,force:true};st.h.force=true;runHealthForce(im,m)}}
 else if(k==='again'){st.nfShow=false;const wasLive=dev()!=='desktop';stop();render(m);if(wasLive)startCam(m)}
 else if(k==='auto'){st.auto=!st.auto;st.lockId=null;st.live=null;b.classList.toggle('on',st.auto);b.setAttribute('aria-pressed',st.auto);b.querySelector('span').textContent='Auto '+(st.auto?'on':'off');const r=m.querySelector('.reticle');if(r){r.querySelector('.scanl')?.remove();if(st.auto)r.insertAdjacentHTML('beforeend','<span class="scanl"></span>')}paintLive(m)}
 else if(k==='torch'){st.torch=!st.torch;try{st.stream.getVideoTracks()[0].applyConstraints({advanced:[{torch:st.torch}]})}catch(_){}b.classList.toggle('on',st.torch)}
 else if(k==='snap'){const v=m.querySelector('#camv');if(!v||!v.videoWidth)return;const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);const img=new Image();img.onload=()=>run(img,m);img.src=c.toDataURL('image/jpeg',.92)}});
document.addEventListener('paste',e=>{if(A.S.sheet!=='scan'||st.mode!=='cam')return;const it=[...(e.clipboardData||{}).items||[]].find(i=>i.type.startsWith('image/'));if(it){const f=it.getAsFile();if(f)loadFile(f,document.getElementById('modal'))}});
/*TANKCHECK-START*/
/* ===== Tank check: photo of the whole aquarium -> spot fish & plants on-device (DINOv2 tiles), visual check,
   owner confirms what is really in the tank, then a full report from TankMates' compatibility engine
   (+ optional Claude vision review). Never claims certainty it does not have. ===== */
const TK={img:null,busy:false,prog:0,det:null,sel:{fish:{},plants:{}},L:'',filter:'yes',heater:'yes',light:'medium',vis:null,ai:null,err:null,fromTank:null,saved:null};
function tkReset(){Object.assign(TK,{img:null,busy:false,prog:0,det:null,sel:{fish:{},plants:{}},L:'',filter:'yes',heater:'yes',light:'medium',vis:null,ai:null,err:null,fromTank:null,saved:null})}
function dScore(f){const {P,W,G,meta,C,d,np}=DN;const gz=[0,1,2].map(k=>{let z=meta.gb[k];for(let j=0;j<d;j++)z+=f[j]*G[j*3+k];return z*meta.gT});const gm=Math.max(...gz),ge=gz.map(z=>Math.exp(z-gm)),gs=ge[0]+ge[1]+ge[2];
 const kn=new Float32Array(C).fill(-1);let rawA=0,rawP=0;for(let i=0;i<np;i++){let v=0;const o=i*d;for(let j=0;j<d;j++)v+=f[j]*P[o+j];const c=meta.pl[i];if(v>kn[c])kn[c]=v;if(meta.kind[c]===0){if(v>rawA)rawA=v}else if(v>rawP)rawP=v}
 const z=new Float64Array(C);let zm=-1e9;for(let c=0;c<C;c++){let v=meta.b[c];for(let j=0;j<d;j++)v+=f[j]*W[j*C+c];z[c]=(v*meta.T0+meta.a*kn[c])*meta.T;if(z[c]>zm)zm=z[c]}
 const best=k=>{let s=0,bi=-1,bv=0;for(let c=0;c<C;c++){if(meta.kind[c]!==k)continue;const e=Math.exp(z[c]-zm);s+=e;if(e>bv){bv=e;bi=c}}return bi<0?null:{id:meta.ids[bi],p:bv/s}};
 return{pa:ge[0]/gs,pp:ge[1]/gs,rawA,rawP,fish:best(0),plant:best(1)}}
async function tkDetect(img){await dEnsure();const w=img.naturalWidth,h=img.naturalHeight,m=Math.min(w,h),boxes=[null];
 for(const g of [2,3]){const s=Math.min(m,Math.max(w,h)/g*1.15);for(let r=0;r<g;r++)for(let c=0;c<g;c++){const cx=(c+.5)*w/g,cy=(r+.5)*h/g;boxes.push([Math.max(0,Math.min(w-s,cx-s/2)),Math.max(0,Math.min(h-s,cy-s/2)),s])}}
 const cv=boxes.map(b=>toCanvas(img,b));cv.push(padCanvas(img));const F=[];
 for(let i=0;i<cv.length;i+=4){F.push(...await dFeats(cv.slice(i,i+4)));TK.prog=Math.round(F.length/cv.length*100);const m2=document.getElementById('modal');if(A.S.sheet==='scan'&&st.mode==='tank'&&m2){const pg=m2.querySelector('.tkprog i');if(pg)pg.style.width=TK.prog+'%'}}
 const fish={},plants={};let anyA=0,anyP=0;
 F.forEach(f=>{const r=dScore(f);anyA=Math.max(anyA,r.pa);anyP=Math.max(anyP,r.pp);
  if(r.pa>=.55&&r.rawA>=.55&&r.fish&&r.fish.p>=.35){const o=fish[r.fish.id]=fish[r.fish.id]||{p:0,hits:0};o.p=Math.max(o.p,r.fish.p);o.hits++}
  if(r.pp>=.55&&r.rawP>=.5&&r.plant&&r.plant.p>=.35){const o=plants[r.plant.id]=plants[r.plant.id]||{p:0,hits:0};o.p=Math.max(o.p,r.plant.p);o.hits++}});
 const keep=o=>Object.entries(o).filter(([id,v])=>A.BY[id]&&(v.p>=.5||(v.hits>=2&&v.p>=.35))).sort((a,b)=>b[1].p-a[1].p);
 /* 4 Oct: one fish seen in several crops can come back as two close relatives (e.g. red-bellied + black piranha). Keep only the strongest of each genus / look-alike group and offer the others as "could also be". */
 const gen=id=>((A.BY[id]&&A.BY[id].sci)||'').split(' ')[0].toLowerCase(),tw=(typeof TWINS!=='undefined'?TWINS:{});const fk=[];
 keep(fish).forEach(([id,v])=>{const last=id=>((A.BY[id]&&A.BY[id].n)||'').toLowerCase().replace(/\(.*\)/,'').trim().split(' ').pop();const host=fk.find(o=>(gen(o.id)&&gen(o.id)===gen(id))||(tw[o.id]||[]).includes(id)||(last(o.id)===last(id)&&v.hits<=1&&o.hits>=3&&v.p<.75));if(host&&v.p<=host.p+0.05){(host.alt=host.alt||[]).push(id);host.p=Math.min(host.p,.69)}else fk.push({id,p:v.p,hits:v.hits})});
 return{fish:fk.slice(0,8),plants:keep(plants).slice(0,6).map(([id,v])=>({id,p:v.p,hits:v.hits})),aquarium:anyA}}
/* simple, honest image measurements */
function tkVision(img){const W=160,H=Math.max(40,Math.round(160*img.naturalHeight/img.naturalWidth)),c=document.createElement('canvas');c.width=W;c.height=H;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(img,0,0,W,H);const d=g.getImageData(0,0,W,H).data;
 let sr=0,sg=0,sb=0,sl=0,sl2=0,green=0,warm=0,n=W*H;const lum=new Float32Array(n);
 for(let i=0;i<n;i++){const r=d[i*4],gg=d[i*4+1],b=d[i*4+2];sr+=r;sg+=gg;sb+=b;const l=.299*r+.587*gg+.114*b;lum[i]=l;sl+=l;sl2+=l*l;const mx=Math.max(r,gg,b),mn=Math.min(r,gg,b),sat=mx?(mx-mn)/mx:0;let hue=0;if(mx!==mn){if(mx===gg)hue=60*((b-r)/(mx-mn))+120;else if(mx===r)hue=(60*((gg-b)/(mx-mn))+360)%360;else hue=60*((r-gg)/(mx-mn))+240}if(hue>=70&&hue<=170&&sat>.25&&mx>50)green++;if(hue>=22&&hue<=55&&sat>.3&&sat<.85&&mx>70)warm++}
 const R=sr/n,Gm=sg/n,B=sb/n,mean=sl/n,sd=Math.sqrt(Math.max(0,sl2/n-mean*mean));
 let open=0,cells=0;const cs=8;for(let y=Math.floor(H*.2);y<H*.7-cs;y+=cs)for(let x=0;x<W-cs;x+=cs){let e=0;for(let yy=y;yy<y+cs;yy++)for(let xx=x;xx<x+cs-1;xx++)e+=Math.abs(lum[yy*W+xx+1]-lum[yy*W+xx]);cells++;if(e/(cs*cs)<4)open++}
 return{mean,sd,R,G:Gm,B,plantCover:green/n,warm:warm/n,open:cells?open/cells:0}}
function tkVisionNotes(v){const o=[];if(!v)return o;
 if(v.mean<45)o.push(['warn','The photo is very dark','Turn the tank light on (room lights off) for a clearer check. Dark photos hide fish and plants.']);
 if(v.mean>215)o.push(['tip','The photo is very bright','Glare or flash can hide details. Take it straight on with the flash off.']);
 if(v.G>v.R*1.18&&v.G>v.B*1.12&&v.sd<42)o.push(['warn','The water looks green','A green haze usually means floating algae (green water). Reduce light hours, avoid direct sun, do water changes, and consider a UV clarifier.']);
 if(v.warm>.45&&v.mean>60&&v.R>v.B*1.3)o.push(['tip','The water looks tea-coloured','Usually tannins from wood or leaves. Harmless and liked by many soft-water fish; use carbon if you prefer clear water.']);
 if(v.sd<28&&v.mean>80&&!(v.G>v.R*1.18))o.push(['warn','The water may be cloudy','Low contrast across the photo can mean cloudy water (bacterial bloom or fine particles). Check ammonia and nitrite, and don’t overfeed.']);
 if(v.plantCover<.04)o.push(['tip','Very few plants are visible','Plants use up nitrate, compete with algae and give fish cover. Easy starters: Java fern, Anubias, floating plants.']);
 else if(v.plantCover>.55)o.push(['tip','The tank is heavily planted','Great for water quality. Keep an open area at the front for swimming and trim regularly.']);
 if(v.open<.08&&v.plantCover>.25)o.push(['tip','Little open swimming space','Active fish like tetras, danios and rainbows need open water in the middle and front.']);
 return o}
/* map names (from AI) to our species */
function tkFind(name){const q=String(name||'').toLowerCase().replace(/[^a-z ]/g,' ').trim();if(!q)return null;let best=null,bs=0;for(const x of Object.values(A.BY)){if(!x||!x.n||!(x.kind==='sp'||x.kind==='pl'))continue;const names=[x.n,x.sci||'',...(x.aka||[])].map(s=>String(s).toLowerCase());for(const nm of names){if(!nm)continue;const s=nm===q?3:(q.includes(nm)&&nm.length>4)||(nm.includes(q)&&q.length>4)?2:0;if(s>bs){bs=s;best=x}}}return bs?best:null}
function tkTank(){const t=A.newTank('existing');t.shape='custom';t.custom=+TK.L>0?+TK.L:200;t.fish={};t.plants={};
 Object.entries(TK.sel.fish).forEach(([id,n])=>{if(n>0)t.fish[id]={n}});Object.keys(TK.sel.plants).forEach(id=>{t.plants[id]=1});
 const hs0=TK.ai&&TK.ai.hardscape;t.eq.cave=!!(hs0&&hs0.caves);t.eq.wood=!!(hs0&&hs0.wood);
 if(TK.filter==='no')t.eq.filter='none';if(TK.heater==='no')t.eq.heater=false;t.eq.light=TK.light;return t}
const EQ_SKIP=/Heater may be too weak|Keep the heater off|Filter flow is low|Undergravel|Very strong current|Crushed coral|Aqua soil/;
function tkReport(){const t=tkTank(),ids=Object.keys(t.fish),pids=Object.keys(t.plants);if(!ids.length&&!pids.length)return null;
 const c=A.check(t);let items=c.items.filter(i=>i.level!=='good'&&!EQ_SKIP.test(i.title));
 if(!(+TK.L>0))items=items.filter(i=>!/Overstock|Nearly full|tank too small/.test(i.title));
 const hs=TK.ai&&TK.ai.hardscape||{};
 items=items.map(i=>{if(/needs a cave/.test(i.title))return hs.caves?null:Object.assign({},i,{level:'tip',title:i.title.replace('needs a cave','needs a cave to hide in'),text:'If there is no cave yet, add one per fish (clay pot, rock cave or pleco cave).'});
  if(/needs driftwood/.test(i.title))return hs.wood?null:Object.assign({},i,{level:'tip',text:'Make sure there is real driftwood in the tank: it rasps wood for fibre.'});
  if(/needs sand/.test(i.title))return /sand/.test(TK.ai&&TK.ai.substrate||'')?null:Object.assign({},i,{level:'tip'});return i}).filter(Boolean);
 const sec={compat:[],stock:[],plants:[],layout:[],equip:[],water:[]};
 items.forEach(i=>{const T=i.title;if(/ \+ |Only one|own tank|eat the small|Temperatures|pH needs/.test(T))sec.compat.push(i);else if(/Overstock|Nearly full|too small|keep at least|Bowls/.test(T))sec.stock.push(i);else if(/light|CO₂|root in|eat or uproot|grows on|feeds through/.test(T))sec.plants.push(i);else if(/cave|driftwood|sand|land/.test(T))sec.layout.push(i);else if(/heater|filter|Heater|Filter|summer/.test(T))sec.equip.push(i);else sec.water.push(i)});
 if(TK.filter==='unsure')sec.equip.push({level:'warn',title:'Check that a filter is running',text:'Every aquarium needs a working filter to keep ammonia down. Look for a box, sponge or canister with water moving through it.'});
 if(TK.heater==='unsure'&&c.temp&&c.temp[0]>=22)sec.equip.push({level:'warn',title:'Check the water temperature',text:`Your fish need about ${c.temp.join('–')} °C. Use a thermometer; most homes need a heater for this.`});
 tkVisionNotes(TK.vis).forEach(([level,title,text])=>sec.water.push({level,title,text,vis:1}));
 if(TK.ai&&!TK.ai.err){(TK.ai.layout_issues||[]).slice(0,5).forEach(x=>sec.layout.push({level:'warn',title:String(x).slice(0,90),text:'',ai:1}));
  if(TK.ai.algae==='heavy')sec.water.push({level:'warn',title:'Lots of algae visible',text:'Shorten the light period, do larger water changes and add fast-growing plants.',ai:1});
  if(TK.ai.water==='cloudy'&&!sec.water.some(i=>/cloudy/.test(i.title)))sec.water.push({level:'warn',title:'The water looks cloudy',text:'Check ammonia/nitrite and avoid overfeeding.',ai:1})}
 const all=Object.values(sec).flat(),nb=all.filter(i=>i.level==='bad').length,nw=all.filter(i=>i.level==='warn').length,nt=all.filter(i=>i.level==='tip').length;
 const score=Math.max(5,Math.min(+TK.L>0?99:90,100-nb*18-nw*7-nt*2));
 const good=[];if(!sec.compat.length&&ids.length>1)good.push('The fish you confirmed can live together.');if(c.temp)good.push(`Shared temperature range: ${c.temp.join('–')} °C.`);if(c.ph)good.push(`Shared pH range: ${c.ph.join('–')}.`);if(+TK.L>0&&c.pct<=85&&ids.length)good.push(`Stocking about ${c.pct}% of capacity.`);(TK.ai&&TK.ai.good_points||[]).slice(0,3).forEach(x=>good.push(String(x)));
 return{t,c,sec,score,good,nb,nw}}
const TKSEC=[['compat','Fish compatibility','vs'],['stock','Stocking & groups','users'],['plants','Plants & fish together','leaf'],['layout','Layout & decor','layers'],['equip','Equipment','filter'],['water','Water & looks','drop']];
function tkItem(i){const col=i.level==='bad'?'#FF6A57':i.level==='warn'?'#F6B740':'#7FE3D3';return `<div class="tki ${i.level}"><span class="tkd" style="background:${col}"></span><div><b>${esc(i.title)}${i.ai?' <em class="tkai">AI</em>':''}${i.vis?' <em class="tkai">photo</em>':''}</b>${i.text?`<p>${esc(i.text)}</p>`:''}</div></div>`}
function tkChip(id,kind){const x=A.BY[id];if(!x)return '';const n=kind==='fish'?TK.sel.fish[id]:1;const d=TK.det&&(TK.det[kind==='fish'?'fish':'plants']||[]).find(o=>o.id===id);
 return `<div class="tkc"><img src="${D.src(id)}" alt=""><span><b>${esc(x.n)}</b><small>${d?(d.p>=.7&&!TWINS[id]?'Spotted':(d.alt&&d.alt.length?'Maybe — or '+d.alt.map(a=>A.BY[a]&&A.BY[a].n).filter(Boolean).join(' / ')+'. Please check':'Maybe — please check')):'Added by you'}</small>${d&&TWINS[id]?`<small class="tktw">Looks very like: ${TWINS[id].filter(t=>A.BY[t]).map(t=>`<button data-tkswap="${kind}|${id}|${t}">${esc(A.BY[t].n)}</button>`).join(' ')}</small>`:''}</span>${kind==='fish'?`<span class="tkn"><button data-tkn="${id}|-1" aria-label="Fewer">−</button><i>${n}</i><button data-tkn="${id}|1" aria-label="More">+</button></span>`:''}<button class="tkx" data-tkrm="${kind}|${id}" aria-label="Remove">${I('x',14)}</button></div>`}
function tankView(){const tanks=(A.S.tanks||[]).filter(t=>Object.keys(t.fish||{}).length);
 if(!TK.img&&!TK.fromTank)return `<div class="tkhero"><span class="tkhic">${I('tank',34)}</span><h3>Check my whole aquarium</h3><p>Take one photo of the full tank. TankMates looks for the fish and plants it knows, then checks compatibility, stocking, plants, layout and water — and tells you what to fix.</p>
 <ul class="tktips"><li>${I('check',14)}Stand straight in front of the glass, whole tank in view</li><li>${I('check',14)}Tank light on, room lights and flash off</li><li>${I('check',14)}Wait until the fish are spread out</li></ul>
 <div class="tkbtns"><label class="btn grad">${I('camera',17)}Take a photo<input id="tcf" type="file" accept="image/*" capture="environment" hidden></label><label class="btn ghost">${I('image',17)}Choose photo<input id="tcg" type="file" accept="image/*" hidden></label></div>
 ${tanks.length?`<div class="tkor"><span>or check a tank you already saved</span><div class="tksaved">${tanks.slice(0,6).map(t=>`<button class="btn sm ghost" data-tkfrom="${t.id}">${I('tank',14)}${esc(t.name||'My tank')}</button>`).join('')}</div></div>`:''}
 <p class="xs tkpriv">${I('lock',12)} The photo is checked on your device. The optional AI review sends it to Claude only when you tap it.</p></div>`;
 if(TK.busy)return `<div class="tkwork">${TK.img?`<img class="tkph" src="${TK.img.src}" alt="Your aquarium">`:''}<b>Looking for fish and plants…</b><div class="tkprog"><i style="width:${TK.prog}%"></i></div><small>Checking the photo piece by piece on your device.</small></div>`;
 if(TK.err)return `<div class="tkwork"><b style="color:#FF6A57">${esc(TK.err)}</b><button class="btn grad" data-tk="restart">${I('refresh',16)}Try again</button></div>`;
 const R=tkReport(),fishIds=Object.keys(TK.sel.fish),plIds=Object.keys(TK.sel.plants),noA=TK.det&&TK.det.aquarium<.4&&!fishIds.length;
 const opts=Object.values(A.BY).filter(x=>x&&x.n&&(x.kind==='sp'||x.kind==='pl')).map(x=>`<option value="${esc(x.n)}">`).join('');
 const seg=(k,arr)=>`<div class="seg tkseg">${arr.map(([v,l])=>`<button type="button" data-tkset="${k}|${v}" aria-pressed="${TK[k]===v}">${l}</button>`).join('')}</div>`;
 return `<div class="tkgrid"><div class="tkleft">${TK.img?`<img class="tkph" src="${TK.img.src}" alt="Your aquarium">`:`<div class="tkph tkph0">${I('tank',40)}<b>${esc(TK.fromTank.name||'My tank')}</b></div>`}
  <div class="tkbox"><div class="tkh"><b>${I('fish',16)} 1 · What’s in your tank?</b>${TK.det?`<small>${TK.det.fish.length||TK.det.plants.length?'We spotted these. Please fix the names and set how many you have.':'We couldn’t name the animals in this photo. Add them below.'}</small>`:''}</div>
   ${noA?`<p class="tknote">${I('alert',14)} This photo doesn’t look like an aquarium to me. Take a photo of the whole tank, or add your fish by hand.</p>`:''}
   <div class="tkchips">${fishIds.map(id=>tkChip(id,'fish')).join('')}${plIds.map(id=>tkChip(id,'plants')).join('')}${!fishIds.length&&!plIds.length?'<p class="xs muted">Nothing added yet.</p>':''}</div>
   <div class="tkadd"><input id="tkq" list="tklist" placeholder="Add a fish or plant…" autocomplete="off" data-nomod><datalist id="tklist">${opts}</datalist><button class="btn sm grad" data-tk="add">${I('plus',15)}Add</button></div></div>
  <div class="tkbox"><div class="tkh"><b>${I('tank',16)} 2 · About your tank</b><small>Things a photo can’t show.</small></div>
   <label class="tkrow"><span>Water volume</span><span class="tkl"><input id="tkL" type="number" inputmode="numeric" min="5" max="5000" placeholder="e.g. 120" value="${esc(TK.L)}"> L</span></label>
   <div class="tkpre">${[30,60,100,200,300].map(v=>`<button type="button" class="chip" data-tkset="L|${v}" aria-pressed="${+TK.L===v}">${v} L</button>`).join('')}</div>
   <div class="tkrow"><span>Filter running?</span>${seg('filter',[['yes','Yes'],['no','No'],['unsure','Not sure']])}</div>
   <div class="tkrow"><span>Heater?</span>${seg('heater',[['yes','Yes'],['no','No'],['unsure','Not sure']])}</div>
   <div class="tkrow"><span>Light</span>${seg('light',[['low','Low'],['medium','Medium'],['high','Strong']])}</div></div>
  <div class="tkbtns"><button class="btn ghost" data-tk="restart">${I('camera',16)}New photo</button></div></div>
 <div class="tkright">${R?`<div class="tkscore"><div class="tkring" style="--p:${R.score};--c:${R.score>=80?'#45D483':R.score>=55?'#F6B740':'#FF6A57'}"><b>${R.score}</b><small>/100</small></div><div><span class="eyebrow">3 · Your tank check</span><h3>${R.nb?'Some things need fixing':R.nw?'Good, with a few improvements':+TK.L>0?'Looking great':'Good so far'}</h3><p class="sm">${R.nb} serious · ${R.nw} to improve${!(+TK.L>0)?' · add the volume for a stocking check':''}</p></div></div>
  ${TKSEC.map(([k,l,ic])=>R.sec[k].length?`<div class="tksec"><h4>${I(ic,16)} ${l}</h4>${R.sec[k].map(tkItem).join('')}</div>`:'').join('')}
  ${R.good.length?`<div class="tksec good"><h4>${I('check',16)} What’s good</h4>${R.good.map(g=>`<div class="tki tip"><span class="tkd" style="background:#45D483"></span><div><b>${esc(g)}</b></div></div>`).join('')}</div>`:''}
  ${tkAiBlock()}
  <div class="tkbtns"><button class="btn grad" data-tk="save">${I(TK.saved?'check':'plus',16)}${TK.saved?'Saved to My tanks':'Save as my tank'}</button><button class="btn ghost" data-tk="planner">${I('tank',16)}Open in planner</button></div>
  <p class="xs tkpriv">${I('info',12)} Automatic spotting can be wrong: the report uses only the fish and plants you confirm on the left.</p>`
 :`<div class="tkempty">${I('fish',28)}<b>Add the fish and plants in your tank</b><p class="sm">Confirm what we spotted or add them by hand, and your full report appears here.</p></div>${tkAiBlock()}`}</div></div>`}
function tkAiBlock(){if(!TK.img||!AIS)return '';const a=TK.ai;
 if(!a)return `<div class="aivet"><div class="aivh"><span class="aivic">${I('sparkle',20)}</span><div><b>Deep AI review</b><small>Claude looks at your photo: layout, hiding places, plant health, algae, equipment and anything that looks wrong. About 20–30 seconds.</small></div></div><button class="btn grad block" data-tk="ai">${I('sparkle',16)}Run deep AI review</button></div>`;
 if(a.busy)return `<div class="aivet"><div class="aivh"><span class="spin"></span><div><b>Claude is looking at your aquarium…</b><small>This takes about 20–30 seconds.</small></div></div></div>`;
 if(a.err)return `<div class="aivet"><b style="color:#FF6A57">${esc(a.err)}</b></div>`;
 return `<div class="aivet"><div class="aivh"><span class="aivic">${I('sparkle',20)}</span><div><b>AI review</b><small>${esc(a.summary||'')}</small></div></div>${(a.actions||[]).length?`<ol class="tkact">${a.actions.slice(0,6).map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:''}${(a.unmatched||[]).length?`<p class="xs muted">The AI also mentioned: ${a.unmatched.map(esc).join(', ')} (not in our encyclopedia, so not checked).</p>`:''}</div>`}
async function tkRunAI(m){if(!AIS||!TK.img)return;TK.ai={busy:true};render(m);
 const conf=Object.keys(TK.sel.fish).map(id=>A.BY[id]&&A.BY[id].n).filter(Boolean),confP=Object.keys(TK.sel.plants).map(id=>A.BY[id]&&A.BY[id].n).filter(Boolean);
 const prompt=`You are an expert aquarist reviewing a photo of a home aquarium for its owner. Look carefully at what is VISIBLE.
The owner says the tank holds: fish ${conf.join(', ')||'unknown'}; plants ${confP.join(', ')||'unknown'}; about ${+TK.L>0?TK.L+' litres':'unknown volume'}; filter ${TK.filter}; heater ${TK.heater}.
Identify fish/invertebrates and plants you can see (common names; only if reasonably sure), and assess layout (hiding places, caves, driftwood, rocks, open swimming space, plant cover, substrate), water appearance (clear/cloudy/green/tea), algae, visible equipment, and any welfare problems (overcrowding, fish that clearly do not belong together, plants that need more light, sharp decor for long-finned fish, etc.).
Reply with ONLY one JSON object, no markdown:
{"is_aquarium":true,"species_seen":[{"name":"","count":0,"confidence":0.0}],"plants_seen":[{"name":"","confidence":0.0}],"hardscape":{"caves":false,"wood":false,"rocks":false},"substrate":"sand|gravel|soil|bare|unknown","plant_cover":"none|low|medium|high","open_swim_space":"good|limited","water":"clear|cloudy|green|tea|unknown","algae":"none|some|heavy","equipment_visible":{"filter":false,"heater":false,"light":false},"layout_issues":["short, specific"],"good_points":["short"],"actions":["most important first, max 6"],"summary":"two plain sentences"}
Be honest about uncertainty; do not invent fish you cannot see.`;
 try{const blob=await toBlob(TK.img);const r=await AIS.json(prompt,{images:[blob],modelTier:'default'});if(!r||typeof r!=='object')throw {code:'parse'};
  const um=[];(r.species_seen||[]).forEach(s=>{if((s.confidence||0)<.6)return;const x=tkFind(s.name);if(x&&x.kind==='sp'){if(!TK.sel.fish[x.id])TK.sel.fish[x.id]=Math.max(1,Math.min(30,+s.count||1))}else um.push(s.name)});
  (r.plants_seen||[]).forEach(s=>{if((s.confidence||0)<.6)return;const x=tkFind(s.name);if(x&&x.kind==='pl')TK.sel.plants[x.id]=1});r.unmatched=um.slice(0,6);TK.ai=r;try{A.xp(10,'AI tank review')}catch(_){}}
 catch(e){TK.ai={err:e&&e.code==='not_granted'?'The AI review was not allowed. You can allow it next time you tap the button.':e&&e.code==='rate_limited'?'Too many reviews right now. Try again in a minute.':'The AI review could not run right now. Try again later.'}}
 if(A.S.sheet==='scan'&&st.mode==='tank')render(m)}
async function tkLoad(f,m){if(f.type&&!/^image\//.test(f.type)){TK.err='That file is not a photo. Try a JPG or PNG.';render(m);return}
 const img=new Image();img.onload=async()=>{tkReset();TK.img=img;TK.busy=true;TK.vis=tkVision(img);render(m);
  try{const det=await tkDetect(img);TK.det=det;window.__tkdet=det;det.fish.forEach(o=>{TK.sel.fish[o.id]=Math.max(1,Math.min(12,(A.BY[o.id]&&A.BY[o.id].grp)||1))});det.plants.forEach(o=>{TK.sel.plants[o.id]=1});try{A.xp(15,'Tank check');A.stat('tankchecks')}catch(_){}}
  catch(e){console.warn('tank',e);TK.det={fish:[],plants:[],aquarium:1};TK.err=null}
  TK.busy=false;if(A.S.sheet==='scan'&&st.mode==='tank')render(m)};img.onerror=()=>{TK.err='That file could not be opened as a photo.';render(m)};img.src=URL.createObjectURL(f)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-tk],[data-tkn],[data-tkrm],[data-tkset],[data-tkfrom],[data-tkswap]');if(!b||A.S.sheet!=='scan')return;e.preventDefault();const m=document.getElementById('modal'),d=b.dataset;
 const keepScroll=()=>{const bd=m.querySelector('.body');const y=bd?bd.scrollTop:0;render(m);const b2=m.querySelector('.body');if(b2)b2.scrollTop=y};
 if(d.tkswap){const [k,id,t]=d.tkswap.split('|');const box=TK.sel[k==='fish'?'fish':'plants'];box[t]=box[id];delete box[id];keepScroll();return}
 if(d.tkn){const [id,k]=d.tkn.split('|');TK.sel.fish[id]=Math.max(1,Math.min(99,(TK.sel.fish[id]||1)+(+k)));keepScroll();return}
 if(d.tkrm){const [k,id]=d.tkrm.split('|');delete TK.sel[k==='fish'?'fish':'plants'][id];keepScroll();return}
 if(d.tkset){const [k,v]=d.tkset.split('|');TK[k]=k==='L'?String(v):v;keepScroll();return}
 if(d.tkfrom){const t=(A.S.tanks||[]).find(x=>x.id===d.tkfrom);if(!t)return;tkReset();TK.fromTank=t;Object.entries(t.fish||{}).forEach(([id,o])=>{TK.sel.fish[id]=o.n||1});Object.keys(t.plants||{}).forEach(id=>TK.sel.plants[id]=1);try{const v=A.vol?A.vol(t):null;if(v)TK.L=String(Math.round(v.net))}catch(_){}keepScroll();return}
 const k=d.tk;
 if(k==='restart'){tkReset();render(m);return}
 if(k==='add'){const q=m.querySelector('#tkq');const x=q&&tkFind(q.value);if(!x){A.toast&&A.toast('Pick a name from the list');return}if(x.kind==='sp')TK.sel.fish[x.id]=TK.sel.fish[x.id]||Math.max(1,x.grp||1);else TK.sel.plants[x.id]=1;keepScroll();return}
 if(k==='ai'){tkRunAI(m);return}
 if(k==='save'){if(TK.saved)return;const t=tkTank();t.name=TK.fromTank?(TK.fromTank.name+' (checked)'):'My aquarium (Tank check)';if(!(+TK.L>0)){A.toast&&A.toast('Add the water volume first (step 2)');const i=m.querySelector('#tkL');if(i){i.focus();i.scrollIntoView({block:'center'})}return}A.S.tanks.push(t);A.saveTanks();TK.saved=t.id;A.toast&&A.toast('Saved to My tanks');keepScroll();return}
 if(k==='planner'){const t=tkTank();if(!(+TK.L>0))t.custom=60;try{stop()}catch(_){}A.closeSheet();A.startPlan(t,5);return}},true);
document.addEventListener('change',e=>{if(A.S.sheet!=='scan')return;const t=e.target,m=document.getElementById('modal');if(t.id==='tcf'||t.id==='tcg'){const f=t.files[0];if(f)tkLoad(f,m)}if(t.id==='tkL'){TK.L=String(Math.max(0,Math.min(5000,+t.value||0))||'');setTimeout(()=>{const bd=m.querySelector('.body');const y=bd?bd.scrollTop:0;render(m);const b2=m.querySelector('.body');if(b2)b2.scrollTop=y},0)}if(t.id==='tkq'&&tkFind(t.value)){const x=tkFind(t.value);if(x.kind==='sp')TK.sel.fish[x.id]=TK.sel.fish[x.id]||Math.max(1,x.grp||1);else TK.sel.plants[x.id]=1;setTimeout(()=>{const bd=m.querySelector('.body');const y=bd?bd.scrollTop:0;render(m);const b2=m.querySelector('.body');if(b2)b2.scrollTop=y},0)}},true);
/*TANKCHECK-END*/

document.addEventListener('click',e=>{const b=e.target.closest('[data-scan]');if(b&&b.dataset.scan==='tank'){try{stop()}catch(_){}tkReset();st.mode='tank'}},true);
window.SCAN={render(m){document.body.style.overflow='hidden';if(st.auto===undefined)st.auto=true;render(m);ensure().then(()=>paintLive(m)).catch(()=>{});if(st.mode==='cam'&&dev()!=='desktop'&&!st.stream&&!st.img&&!st.denied)startCam(m);else if(st.stream&&dev()!=='desktop')startLoop(m)},stop:()=>{stop();try{tkReset()}catch(_){}},identify,ensure,qvecs};
})();
